import axios from "axios";

export default {
  namespaced: true,
  state: {
    property: {
      id: null,
      hotel: null,
      hotelCharacteristics: [],
      outdoorCharacteristics: [],
      outdoorEquipment: [],
      outdoorFacilityUpOnWeather: null,
      restrictionOutdoorLateSeason: null,
      outdoorAreaSize: 0.0,
      hotelBeachFront: null,
      hotelBeachSeparateRoad: null,
      quietRelaxing: null,
      outsideTheCity: null,
      hasSunLoungers: null,
      sunLoungersOnBeach: null,
      sunLoungersBeachQuantity: null,
      sunLoungersBeachType: null,
      sunLoungersBeachCharges: null,
      sunLoungersBeachIsSeasonal: null,
      sunLoungersBeachDrinkService: null,
      sunLoungersOnPool: null,
      sunLoungersPoolQuantity: null,
      sunLoungersPoolType: null,
      sunLoungersPoolCharges: null,
      sunLoungersPoolIsSeasonal: null,
      sunLoungersPoolDrinkService: null,
      sunLoungersOnGarden: null,
      sunLoungersGardenQuantity: null,
      sunLoungersGardenType: null,
      sunLoungersGardenCharges: null,
      sunLoungersGardenIsSeasonal: null,
      sunLoungersGardenDrinkService: null,
      sunLoungersOnLake: null,
      sunLoungersLakeQuantity: null,
      sunLoungersLakeType: null,
      sunLoungersLakeCharges: null,
      sunLoungersLakeIsSeasonal: null,
      sunLoungersLakeDrinkService: null,
      sunLoungersOnSunTerrace: null,
      sunLoungersSunTerraceQuantity: null,
      sunLoungersSunTerraceType: null,
      sunLoungersSunTerraceCharges: null,
      sunLoungersSunTerraceIsSeasonal: null,
      sunLoungersSunTerraceDrinkService: null,
      hasParasols: null,
      parasolsAtBeach: null,
      parasolsAtBeachQuantity: null,
      parasolsAtBeachCharges: null,
      parasolsAtBeachSeasonal: null,
      parasolsAtBeachLocalSupplier: null,
      parasolsAtPool: null,
      parasolsAtPoolQuantity: null,
      parasolsAtPoolCharges: null,
      parasolsAtPoolSeasonal: null,
      parasolsAtGarden: null,
      parasolsAtGardenQuantity: null,
      parasolsAtGardenCharges: null,
      parasolsAtGardenSeasonal: null,
      parasolsAtLake: null,
      parasolsAtLakeQuantity: null,
      parasolsAtLakeCharges: null,
      parasolsAtLakeSeasonal: null,
      parasolsAtLakeLocalSupplier: null,
      parasolsSunTerrace: null,
      parasolsSunTerraceQuantity: null,
      parasolsSunTerraceCharges: null,
      parasolsSunTerraceSeasonal: null,
      hasTowels: null,
      towelsOnBeach: null,
      towelsOnBeachCharges: null,
      towelsOnBeachAdditionalCharge: null,
      towelsOnPool: null,
      towelsOnPoolCharges: null,
      towelsOnPoolAdditionalCharge: null,
      hotelHasSwimmingPool: null,
      swimmingPoolsNumber: null,
      swimmingPoolsTotalSize: null,
      swimmingPoolsIsHeated: null,
      swimmingPoolsCoolable: null,
      swimmingPoolsIsAdultOnly: null,
      swimmingPoolsType: null,
      swimmingPoolsHasKids: null,
      swimmingPoolsOnWeather: null,
      hotelHasAquaPark: null,
      aquaWaterHeatable: null,
      aquaWaterCoolable: null,
      aquaParkSlidesCount: null,
      aquaParkCharges: null,
      aquaParkPrice: null,
      aquaParkPriceCurrency: null,
      aquaParkSize: null,
      aquaParkWater: null,
      hotelBuildingsCount: null,
      hotelBungalowsCount: null,
      hotelVillasCount: null,
      hotelTotalAmountUnits: null,
      hotelUnitsWheelchair: null,
      hotelFacilityServices: [],
      hotelCreditCards: [],
      hotelLiftsAvailable: null,
      hotelLiftsCount: null,
      hotelLiftsPanoramicAvail: null,
      hotelLiftsPanoramicCount: null,
      hotelReceptionAvailable: null,
      hotelReceptionAllDay: null,
      hotelHasLobbyArea: null,
      hotelHasLaundryCleaning: null,
      hotelLaundryCharges: null,
      hotelWifiCheck: null,
      hotelWifiCharges: null,
      hotelWifiLocations: null,
      shuttleWithinHotel: null,
      hotelSafeCheck: null,
      hotelSafeCharges: null,
      hotelSafePrice: null,
      hotelSafePriceCurrency: null,
      hotelHasDiscoClub: null,
      hotelDiscoClubLocation: null,
      hotelDiscoClubEntrance: null,
      hotelDiscoClubDrinks: null,
      hotelParkingAvailable: null,
      hotelParkingCharges: null,
      hotelParkingPrice: null,
      hotelParkingSlotsCount: null,
      hotelParkingOnRequest: null,
      hotelParkingReservationRequired: null,
      hotelParkingIsGuarded: null,
      hotelParkingIsUnguarded: null,
      publicCarParkingAvailable: null,
      publicCarParkingCharges: null,
      publicCarParkingPrice: null,
      publicCarParkingSlotsCount: null,
      publicCarParkingIsGuarded: null,
      carParkingSideRoadAvailable: null,
      carParkingSideRoadCharges: null,
      carParkingSideRoadPrice: null,
      carParkingSideRoadLimitedArea: null,
      carParkingSideRoadIsGuarded: null,
      nearbyCarParkingAvailable: null,
      nearbyCarParkingCharges: null,
      nearbyCarParkingPrice: null,
      nearbyCarParkingSlotsCount: null,
      nearbyCarParkingIsGuarded: null,
      publicUnderGroundParkingAvailable: null,
      publicUnderGroundParkingCharges: null,
      publicUnderGroundParkingPrice: null,
      publicUnderGroundParkingSlotsCount: null,
      publicUnderGroundParkingIsGuarded: null,
      hotelRestaurantsCount: null,
      hotelBarsCount: null,
      hotelGroundSize: null,
      hotelHasCafes: null,
      hotelCafesNumber: null,
      hotelDoctorConsult: null,
      hotelDoctorConsultCharges: null,
      hotelNearestAtm: null,
    },
    errors: [],
  },
  mutations: {
    updateProperty(state, newInfo) {
      state.property = newInfo;
    },
    updateErrors(state, newInfo) {
      /* console.log("commit here", newInfo); */
      state.errors = newInfo;
    },
  },
  actions: {
    validate(context, newInfo) {
      context.commit("updateErrors", newInfo);
    },
    postInfo(context, newInfo) {
      axios.defaults.headers.common.Authorization = `Token ${context.rootState.user.token}`;
      /* console.log(`Token is ${context.rootState.user.token}`); */
      /* console.log(newInfo); */
      const requestMethod = newInfo.id ? "put" : "post";
      const requestUrl = newInfo.id
        ? `http://127.0.0.1:8000/api/facts/facility/update/${newInfo.id}/`
        : "http://127.0.0.1:8000/api/facts/facility/create/";
      return new Promise((resolve, reject) => {
        axios({
          method: requestMethod,
          url: requestUrl,
          data: newInfo,
        })
          .then((response) => {
            const savedInfo = {
              id: response.data.hotel,
              hotel: response.data.hotel.id,
              hotelCharacteristics: response.data.hotel_characteristics,
              outdoorCharacteristics: response.data.outdoor_characteristics,
              outdoorEquipment: response.data.outdoor_equipment,
              outdoorFacilityUpOnWeather: response.data.outdoor_facility_up_on_weather,
              restrictionOutdoorLateSeason: response.data.restriction_outdoor_late_season,
              outdoorAreaSize: response.data.outdoor_area_size,
              hotelBeachFront: response.data.hotel_beach_front,
              hotelBeachSeparateRoad: response.data.hotel_beach_separate_road,
              quietRelaxing: response.data.quiet_relaxing,
              outsideTheCity: response.data.outside_the_city,
              hasSunLoungers: response.data.has_sun_loungers,
              sunLoungersOnBeach: response.data.sun_loungers_on_beach,
              sunLoungersBeachQuantity: response.data.sun_loungers_beach_quantity,
              sunLoungersBeachType: response.data.sun_loungers_beach_type,
              sunLoungersBeachCharges: response.data.sun_loungers_beach_charges,
              sunLoungersBeachIsSeasonal: response.data.sun_loungers_beach_is_seasonal,
              sunLoungersBeachDrinkService: response.data.sun_loungers_beach_drink_service,
              sunLoungersOnPool: response.data.sun_loungers_on_pool,
              sunLoungersPoolQuantity: response.data.sun_loungers_pool_quantity,
              sunLoungersPoolType: response.data.sun_loungers_pool_type,
              sunLoungersPoolCharges: response.data.sun_loungers_pool_charges,
              sunLoungersPoolIsSeasonal: response.data.sun_loungers_pool_is_seasonal,
              sunLoungersPoolDrinkService: response.data.sun_loungers_pool_drink_service,
              sunLoungersOnGarden: response.data.sun_loungers_on_garden,
              sunLoungersGardenQuantity: response.data.sun_loungers_garden_quantity,
              sunLoungersGardenType: response.data.sun_loungers_garden_type,
              sunLoungersGardenCharges: response.data.sun_loungers_garden_charges,
              sunLoungersGardenIsSeasonal: response.data.sun_loungers_garden_is_seasonal,
              sunLoungersGardenDrinkService: response.data.sun_loungers_garden_drink_service,
              sunLoungersOnLake: response.data.sun_loungers_on_lake,
              sunLoungersLakeQuantity: response.data.sun_loungers_lake_quantity,
              sunLoungersLakeType: response.data.sun_loungers_lake_type,
              sunLoungersLakeCharges: response.data.sun_loungers_lake_charges,
              sunLoungersLakeIsSeasonal: response.data.sun_loungers_lake_is_seasonal,
              sunLoungersLakeDrinkService: response.data.sun_loungers_lake_drink_service,
              sunLoungersOnSunTerrace: response.data.sun_loungers_on_sun_terrace,
              sunLoungersSunTerraceQuantity: response.data.sun_loungers_sun_terrace_quantity,
              sunLoungersSunTerraceType: response.data.sun_loungers_sun_terrace_type,
              sunLoungersSunTerraceCharges: response.data.sun_loungers_sun_terrace_charges,
              sunLoungersSunTerraceIsSeasonal: response.data.sun_loungers_sun_terrace_is_seasonal,
              sunLoungersSunTerraceDrinkService:
                response.data.sun_loungers_sun_terrace_drink_service,
              hasParasols: response.data.has_parasols,
              parasolsAtBeach: response.data.parasols_at_beach,
              parasolsAtBeachQuantity: response.data.parasols_at_beach_quantity,
              parasolsAtBeachCharges: response.data.parasols_at_beach_charges,
              parasolsAtBeachSeasonal: response.data.parasols_at_beach_seasonal,
              parasolsAtBeachLocalSupplier: response.data.parasols_at_beach_local_supplier,
              parasolsAtPool: response.data.parasols_at_pool,
              parasolsAtPoolQuantity: response.data.parasols_at_pool_quantity,
              parasolsAtPoolCharges: response.data.parasols_at_pool_charges,
              parasolsAtPoolSeasonal: response.data.parasols_at_pool_seasonal,
              parasolsAtGarden: response.data.parasols_at_garden,
              parasolsAtGardenQuantity: response.data.parasols_at_garden_quantity,
              parasolsAtGardenCharges: response.data.parasols_at_garden_charges,
              parasolsAtGardenSeasonal: response.data.parasols_at_garden_seasonal,
              parasolsAtLake: response.data.parasols_at_lake,
              parasolsAtLakeQuantity: response.data.parasols_at_lake_quantity,
              parasolsAtLakeCharges: response.data.parasols_at_lake_charges,
              parasolsAtLakeSeasonal: response.data.parasols_at_lake_seasonal,
              parasolsAtLakeLocalSupplier: response.data.parasols_at_lake_local_supplier,
              parasolsSunTerrace: response.data.parasols_sun_terrace,
              parasolsSunTerraceQuantity: response.data.parasols_sun_terrace_quantity,
              parasolsSunTerraceCharges: response.data.parasols_sun_terrace_charges,
              parasolsSunTerraceSeasonal: response.data.parasols_sun_terrace_seasonal,
              hasTowels: response.data.has_towels,
              towelsOnBeach: response.data.towels_on_beach,
              towelsOnBeachCharges: response.data.towels_on_beach_charges,
              towelsOnBeachAdditionalCharge: response.data.towels_on_beach_additional_charge,
              towelsOnPool: response.data.towels_on_pool,
              towelsOnPoolCharges: response.data.towels_on_pool_charges,
              towelsOnPoolAdditionalCharge: response.data.towels_on_pool_additional_charge,
              hotelHasSwimmingPool: response.data.hotel_has_swimming_pool,
              swimmingPoolsNumber: response.data.swimming_pools_number,
              swimmingPoolsTotalSize: response.data.swimming_pools_total_size,
              swimmingPoolsIsHeated: response.data.swimming_pools_is_heated,
              swimmingPoolsCoolable: response.data.swimming_pools_coolable,
              swimmingPoolsIsAdultOnly: response.data.swimming_pools_is_adult_only,
              swimmingPoolsType: response.data.swimming_pools_type || null,
              swimmingPoolsHasKids: response.data.swimming_pools_has_kids || null,
              swimmingPoolsOnWeather: response.data.swimming_pools_on_weather,
              swimmingPoolsSeasonal: response.data.swimming_pools_seasonal,
              hotelHasAquaPark: response.data.hotel_has_aqua_park,
              aquaWaterHeatable: response.data.aqua_water_heatable,
              aquaWaterCoolable: response.data.aqua_water_coolable,
              aquaParkSlidesCount: response.data.aqua_park_slides_count,
              aquaParkCharges: response.data.aqua_park_charges,
              aquaParkPrice: response.data.aqua_park_price,
              aquaParkPriceCurrency: response.data.aqua_park_price_currency,
              aquaParkSize: response.data.aqua_park_size,
              aquaParkWater: response.data.aqua_park_water || null,
              hotelBuildingsCount: response.data.hotel_buildings_count,
              hotelBungalowsCount: response.data.hotel_bungalows_count,
              hotelVillasCount: response.data.hotel_villas_count,
              hotelTotalAmountUnits: response.data.hotel_total_amount_units,
              hotelUnitsWheelchair: response.data.hotel_units_wheelchair,
              hotelFacilityServices: response.data.hotel_facility_services,
              hotelCreditCards: response.data.hotel_credit_cards,
              hotelLiftsAvailable: response.data.hotel_lifts_available,
              hotelLiftsCount: response.data.hotel_lifts_count,
              hotelLiftsPanoramicAvail: response.data.hotel_lifts_panoramic_avail,
              hotelLiftsPanoramicCount: response.data.hotel_lifts_panoramic_count,
              hotelReceptionAvailable: response.data.hotel_reception_available,
              hotelReceptionAllDay: response.data.hotel_reception_all_day,
              hotelHasLobbyArea: response.data.hotel_has_lobby_area,
              hotelHasLaundryCleaning: response.data.hotel_has_laundry_cleaning,
              hotelLaundryCharges: response.data.hotel_laundry_charges,
              hotelWifiCheck: response.data.hotel_wifi_check,
              hotelWifiCharges: response.data.hotel_wifi_charges,
              hotelWifiLocations: response.data.hotel_wifi_locations,
              shuttleWithinHotel: response.data.shuttle_within_hotel,
              hotelSafeCheck: response.data.hotel_safe_check,
              hotelSafeCharges: response.data.hotel_safe_charges,
              hotelSafePrice: response.data.hotel_safe_price,
              hotelSafePriceCurrency: response.data.hotel_safe_price_currency,
              hotelHasDiscoClub: response.data.hotel_has_disco_club,
              hotelDiscoClubLocation: response.data.hotel_disco_club_location,
              hotelDiscoClubEntrance: response.data.hotel_disco_club_entrance,
              hotelDiscoClubDrinks: response.data.hotel_disco_club_drinks,
              hotelParkingAvailable: response.data.hotel_parking_available,
              hotelParkingCharges: response.data.hotel_parking_charges,
              hotelParkingPrice: response.data.hotel_parking_price,
              hotelParkingSlotsCount: response.data.hotel_parking_slots_count,
              hotelParkingOnRequest: response.data.hotel_parking_on_request,
              hotelParkingReservationRequired: response.data.hotel_parking_reservation_required,
              hotelParkingIsGuarded: response.data.hotel_parking_is_guarded,
              hotelParkingIsUnguarded: response.data.hotel_parking_is_unguarded,
              publicCarParkingAvailable: response.data.public_car_parking_available,
              publicCarParkingCharges: response.data.public_car_parking_charges,
              publicCarParkingPrice: response.data.public_car_parking_price,
              publicCarParkingSlotsCount: response.data.public_car_parking_slots_count,
              publicCarParkingIsGuarded: response.data.public_car_parking_is_guarded,
              carParkingSideRoadAvailable: response.data.car_parking_side_road_available,
              carParkingSideRoadCharges: response.data.car_parking_side_road_charges,
              carParkingSideRoadPrice: response.data.car_parking_side_road_price,
              carParkingSideRoadLimitedArea: response.data.car_parking_side_road_limited_area,
              carParkingSideRoadIsGuarded: response.data.car_parking_side_road_is_guarded,
              nearbyCarParkingAvailable: response.data.nearby_car_parking_available,
              nearbyCarParkingCharges: response.data.nearby_car_parking_charges,
              nearbyCarParkingPrice: response.data.nearby_car_parking_price,
              nearbyCarParkingSlotsCount: response.data.nearby_car_parking_slots_count,
              nearbyCarParkingIsGuarded: response.data.nearby_car_parking_is_guarded,
              publicUnderGroundParkingAvailable:
                response.data.public_under_ground_parking_available,
              publicUnderGroundParkingCharges: response.data.public_under_ground_parking_charges,
              publicUnderGroundParkingPrice: response.data.public_under_ground_parking_price,
              // eslint-disable-next-line max-len
              publicUnderGroundParkingSlotsCount:
                response.data.public_under_ground_parking_slots_count,
              publicUnderGroundParkingIsGuarded:
                response.data.public_under_ground_parking_is_guarded,
              hotelRestaurantsCount: response.data.hotel_restaurants_count,
              hotelBarsCount: response.data.hotel_bars_count,
              hotelGroundSize: response.data.hotel_ground_size,
              hotelHasCafes: response.data.hotel_has_cafes,
              hotelCafesNumber: response.data.hotel_cafes_number,
              hotelDoctorConsult: response.data.hotel_doctor_consult,
              hotelDoctorConsultCharges: response.data.hotel_doctor_consult_charges,
              hotelNearestAtm: response.data.hotel_nearest_atm,
            };
            context.commit("updateProperty", savedInfo);
            /* console.log("facility:", savedInfo); */
            resolve(savedInfo);
          })
          .catch((error) => {
            reject(error.response.data);
          });
      });
    },
    getInfo(context, infoId) {
      axios.defaults.headers.common.Authorization = `Token ${context.rootState.user.token}`;
      return new Promise((resolve, reject) => {
        axios({
          method: "get",
          url: `http://127.0.0.1:8000/api/facts/facility/${infoId}/`,
        })
          .then((response) => {
            const retrievedInfo = {
              id: response.data.hotel,
              hotel: response.data.hotel?.id,
              hotelCharacteristics: response.data.hotel_characteristics || [],
              outdoorCharacteristics: response.data.outdoor_characteristics || [],
              outdoorEquipment: response.data.outdoor_equipment || [],
              outdoorFacilityUpOnWeather: response.data.outdoor_facility_up_on_weather,
              restrictionOutdoorLateSeason: response.data.restriction_outdoor_late_season,
              outdoorAreaSize: response.data.outdoor_area_size,
              hotelBeachFront: response.data.hotel_beach_front,
              hotelBeachSeparateRoad: response.data.hotel_beach_separate_road,
              quietRelaxing: response.data.quiet_relaxing,
              outsideTheCity: response.data.outside_the_city,
              hasSunLoungers: response.data.has_sun_loungers,
              sunLoungersOnBeach: response.data.sun_loungers_on_beach,
              sunLoungersBeachQuantity: response.data.sun_loungers_beach_quantity,
              sunLoungersBeachType: response.data.sun_loungers_beach_type,
              sunLoungersBeachCharges: response.data.sun_loungers_beach_charges,
              sunLoungersBeachIsSeasonal: response.data.sun_loungers_beach_is_seasonal,
              sunLoungersBeachDrinkService: response.data.sun_loungers_beach_drink_service,
              sunLoungersOnPool: response.data.sun_loungers_on_pool,
              sunLoungersPoolQuantity: response.data.sun_loungers_pool_quantity,
              sunLoungersPoolType: response.data.sun_loungers_pool_type,
              sunLoungersPoolCharges: response.data.sun_loungers_pool_charges,
              sunLoungersPoolIsSeasonal: response.data.sun_loungers_pool_is_seasonal,
              sunLoungersPoolDrinkService: response.data.sun_loungers_pool_drink_service,
              sunLoungersOnGarden: response.data.sun_loungers_on_garden,
              sunLoungersGardenQuantity: response.data.sun_loungers_garden_quantity,
              sunLoungersGardenType: response.data.sun_loungers_garden_type,
              sunLoungersGardenCharges: response.data.sun_loungers_garden_charges,
              sunLoungersGardenIsSeasonal: response.data.sun_loungers_garden_is_seasonal,
              sunLoungersGardenDrinkService: response.data.sun_loungers_garden_drink_service,
              sunLoungersOnLake: response.data.sun_loungers_on_lake,
              sunLoungersLakeQuantity: response.data.sun_loungers_lake_quantity,
              sunLoungersLakeType: response.data.sun_loungers_lake_type,
              sunLoungersLakeCharges: response.data.sun_loungers_lake_charges,
              sunLoungersLakeIsSeasonal: response.data.sun_loungers_lake_is_seasonal,
              sunLoungersLakeDrinkService: response.data.sun_loungers_lake_drink_service,
              sunLoungersOnSunTerrace: response.data.sun_loungers_on_sun_terrace,
              sunLoungersSunTerraceQuantity: response.data.sun_loungers_sun_terrace_quantity,
              sunLoungersSunTerraceType: response.data.sun_loungers_sun_terrace_type,
              sunLoungersSunTerraceCharges: response.data.sun_loungers_sun_terrace_charges,
              sunLoungersSunTerraceIsSeasonal: response.data.sun_loungers_sun_terrace_is_seasonal,
              sunLoungersSunTerraceDrinkService:
                response.data.sun_loungers_sun_terrace_drink_service,
              hasParasols: response.data.has_parasols,
              parasolsAtBeach: response.data.parasols_at_beach,
              parasolsAtBeachQuantity: response.data.parasols_at_beach_quantity,
              parasolsAtBeachCharges: response.data.parasols_at_beach_charges,
              parasolsAtBeachSeasonal: response.data.parasols_at_beach_seasonal,
              parasolsAtBeachLocalSupplier: response.data.parasols_at_beach_local_supplier,
              parasolsAtPool: response.data.parasols_at_pool,
              parasolsAtPoolQuantity: response.data.parasols_at_pool_quantity,
              parasolsAtPoolCharges: response.data.parasols_at_pool_charges,
              parasolsAtPoolSeasonal: response.data.parasols_at_pool_seasonal,
              parasolsAtGarden: response.data.parasols_at_garden,
              parasolsAtGardenQuantity: response.data.parasols_at_garden_quantity,
              parasolsAtGardenCharges: response.data.parasols_at_garden_charges,
              parasolsAtGardenSeasonal: response.data.parasols_at_garden_seasonal,
              parasolsAtLake: response.data.parasols_at_lake,
              parasolsAtLakeQuantity: response.data.parasols_at_lake_quantity,
              parasolsAtLakeCharges: response.data.parasols_at_lake_charges,
              parasolsAtLakeSeasonal: response.data.parasols_at_lake_seasonal,
              parasolsAtLakeLocalSupplier: response.data.parasols_at_lake_local_supplier,
              parasolsSunTerrace: response.data.parasols_sun_terrace,
              parasolsSunTerraceQuantity: response.data.parasols_sun_terrace_quantity,
              parasolsSunTerraceCharges: response.data.parasols_sun_terrace_charges,
              parasolsSunTerraceSeasonal: response.data.parasols_sun_terrace_seasonal,
              hasTowels: response.data.has_towels,
              towelsOnBeach: response.data.towels_on_beach,
              towelsOnBeachCharges: response.data.towels_on_beach_charges,
              towelsOnBeachAdditionalCharge: response.data.towels_on_beach_additional_charge,
              towelsOnPool: response.data.towels_on_pool,
              towelsOnPoolCharges: response.data.towels_on_pool_charges,
              towelsOnPoolAdditionalCharge: response.data.towels_on_pool_additional_charge,
              hotelHasSwimmingPool: response.data.hotel_has_swimming_pool,
              swimmingPoolsNumber: response.data.swimming_pools_number,
              swimmingPoolsTotalSize: response.data.swimming_pools_total_size,
              swimmingPoolsIsHeated: response.data.swimming_pools_is_heated,
              swimmingPoolsCoolable: response.data.swimming_pools_coolable,
              swimmingPoolsIsAdultOnly: response.data.swimming_pools_is_adult_only,
              swimmingPoolsType: response.data.swimming_pools_type || null,
              swimmingPoolsHasKids: response.data.swimming_pools_has_kids || null,
              swimmingPoolsOnWeather: response.data.swimming_pools_on_weather,
              swimmingPoolsSeasonal: response.data.swimming_pools_seasonal,
              hotelHasAquaPark: response.data.hotel_has_aqua_park,
              aquaWaterHeatable: response.data.aqua_water_heatable,
              aquaWaterCoolable: response.data.aqua_water_coolable,
              aquaParkSlidesCount: response.data.aqua_park_slides_count,
              aquaParkCharges: response.data.aqua_park_charges,
              aquaParkPrice: response.data.aqua_park_price,
              aquaParkPriceCurrency: response.data.aqua_park_price_currency,
              aquaParkSize: response.data.aqua_park_size,
              aquaParkWater: response.data.aqua_park_water || null,
              hotelBuildingsCount: response.data.hotel_buildings_count,
              hotelBungalowsCount: response.data.hotel_bungalows_count,
              hotelVillasCount: response.data.hotel_villas_count,
              hotelTotalAmountUnits: response.data.hotel_total_amount_units,
              hotelUnitsWheelchair: response.data.hotel_units_wheelchair,
              hotelFacilityServices: response.data.hotel_facility_services || [],
              hotelCreditCards: response.data.hotel_credit_cards || [],
              hotelLiftsAvailable: response.data.hotel_lifts_available,
              hotelLiftsCount: response.data.hotel_lifts_count,
              hotelLiftsPanoramicAvail: response.data.hotel_lifts_panoramic_avail,
              hotelLiftsPanoramicCount: response.data.hotel_lifts_panoramic_count,
              hotelReceptionAvailable: response.data.hotel_reception_available,
              hotelReceptionAllDay: response.data.hotel_reception_all_day,
              hotelHasLobbyArea: response.data.hotel_has_lobby_area,
              hotelHasLaundryCleaning: response.data.hotel_has_laundry_cleaning,
              hotelLaundryCharges: response.data.hotel_laundry_charges,
              hotelWifiCheck: response.data.hotel_wifi_check,
              hotelWifiCharges: response.data.hotel_wifi_charges,
              hotelWifiLocations: response.data.hotel_wifi_locations,
              shuttleWithinHotel: response.data.shuttle_within_hotel,
              hotelSafeCheck: response.data.hotel_safe_check,
              hotelSafeCharges: response.data.hotel_safe_charges,
              hotelSafePrice: response.data.hotel_safe_price,
              hotelSafePriceCurrency: response.data.hotel_safe_price_currency,
              hotelHasDiscoClub: response.data.hotel_has_disco_club,
              hotelDiscoClubLocation: response.data.hotel_disco_club_location,
              hotelDiscoClubEntrance: response.data.hotel_disco_club_entrance,
              hotelDiscoClubDrinks: response.data.hotel_disco_club_drinks,
              hotelParkingAvailable: response.data.hotel_parking_available,
              hotelParkingCharges: response.data.hotel_parking_charges,
              hotelParkingPrice: response.data.hotel_parking_price,
              hotelParkingSlotsCount: response.data.hotel_parking_slots_count,
              hotelParkingOnRequest: response.data.hotel_parking_on_request,
              hotelParkingReservationRequired: response.data.hotel_parking_reservation_required,
              hotelParkingIsGuarded: response.data.hotel_parking_is_guarded,
              hotelParkingIsUnguarded: response.data.hotel_parking_is_unguarded,
              publicCarParkingAvailable: response.data.public_car_parking_available,
              publicCarParkingCharges: response.data.public_car_parking_charges,
              publicCarParkingPrice: response.data.public_car_parking_price,
              publicCarParkingSlotsCount: response.data.public_car_parking_slots_count,
              publicCarParkingIsGuarded: response.data.public_car_parking_is_guarded,
              carParkingSideRoadAvailable: response.data.car_parking_side_road_available,
              carParkingSideRoadCharges: response.data.car_parking_side_road_charges,
              carParkingSideRoadPrice: response.data.car_parking_side_road_price,
              carParkingSideRoadLimitedArea: response.data.car_parking_side_road_limited_area,
              carParkingSideRoadIsGuarded: response.data.car_parking_side_road_is_guarded,
              nearbyCarParkingAvailable: response.data.nearby_car_parking_available,
              nearbyCarParkingCharges: response.data.nearby_car_parking_charges,
              nearbyCarParkingPrice: response.data.nearby_car_parking_price,
              nearbyCarParkingSlotsCount: response.data.nearby_car_parking_slots_count,
              nearbyCarParkingIsGuarded: response.data.nearby_car_parking_is_guarded,
              publicUnderGroundParkingAvailable:
                response.data.public_under_ground_parking_available,
              publicUnderGroundParkingCharges: response.data.public_under_ground_parking_charges,
              publicUnderGroundParkingPrice: response.data.public_under_ground_parking_price,
              // eslint-disable-next-line max-len
              publicUnderGroundParkingSlotsCount:
                response.data.public_under_ground_parking_slots_count,
              publicUnderGroundParkingIsGuarded:
                response.data.public_under_ground_parking_is_guarded,
              hotelRestaurantsCount: response.data.hotel_restaurants_count,
              hotelBarsCount: response.data.hotel_bars_count,
              hotelGroundSize: response.data.hotel_ground_size,
              hotelHasCafes: response.data.hotel_has_cafes,
              hotelCafesNumber: response.data.hotel_cafes_number,
              hotelDoctorConsult: response.data.hotel_doctor_consult,
              hotelDoctorConsultCharges: response.data.hotel_doctor_consult_charges,
              hotelNearestAtm: response.data.hotel_nearest_atm,
            };
            context.commit("updateProperty", retrievedInfo);
            resolve(retrievedInfo);
          })
          .catch((error) => {
            reject(error);
          });
      });
    },
  },
  getters: {
    getProperty(state) {
      return state.property;
    },
    getErrors(state) {
      return state.errors;
    },
  },
};
