export default {
  namespaced: true,
  state: {
    locationEnvironment: [
      "in the desert",
      "in the mountains",
      "at the mountainside",
      "at the mountain railway",
      "in hillside location",
      "on rock platau",
      "in the middle of nature",
      "in the valley",
      "in the ski resort",
      "at the ski lift",
      "in coastal area",
      "in island",
      "near the woods",
      "in natural preserve",
      "in the rainforest",
      "in park",
      "in the national park",
      "at the entrance to the national park",
      "amidst vineyards",
      "in an olive grove",
      "at the leisure park",
      "on camp site",
      "in a private concession area",
      "directly at the golf course",
      "central",
      "directly at",
      "opposite of",
      "east",
      "west",
      "south",
      "north",
    ],
    aroundHotel: [
      "in city center",
      "at Airport",
      "in main street",
      "close to city center",
      "in Resorts area",
      "in Touristic area",
      "in Golf parks",
      "close to sea",
      "close to restaurants",
      "close to river",
      "in the old town",
      "in the new town",
      "in the business district",
    ],
    beachCharacteristics: [
      "Sandy",
      "Natural",
      "Natural Reef",
      "Natural preserve",
      "Rocky",
      "Dunes",
      "Shallow water",
      "Deep water",
      "Soft sand",
    ],
    moreBeachInfo: [
      "fresh water bathing jetty",
      "palm trees",
      "relaxing swing",
      "rocks on beach",
      "swimming restricted",
      "few corals",
      "a lot of corals",
      "house reef",
      "boats platfrom",
      "blue flag quality marker",
      "bathing shoes recommended",
      "rocks/stones in water",
      "kids beach toys",
      "palm",
    ],
    beachInformation: [
      "wide",
      "long",
      "panoramic view",
      "some kilometers long",
      "dune beach",
      "rocky beach",
      "shingle beach",
      "lava beach",
      "natural beach",
      "sandy beach",
      "dark",
      "artificial made beach",
      "narrow",
      "white",
      "high current",
    ],
    beachPathType: [
      "path",
      "bridge",
      "underpass",
      "lift",
      "few steps to beach",
      "unpaved road",
      "shuttle car",
    ],
    distanceTypes: [
      { value: null, text: "Select measurment" },
      { value: "meters", text: "meters" },
      { value: "kilometers", text: "kilometers" },
      { value: "miles", text: "miles" },
      { value: "minutes", text: "minutes" },
      { value: "hours", text: "hours" },
    ],
    boardsAvailableOptions: [
      { value: "Room only", text: "without board" },
      { value: "Bed and Breakfast", text: "Bed and Breakfast" },
      { value: "Half Board", text: "Half Board" },
      { value: "Full Board", text: "Full Board" },
      { value: "Full Board Plus", text: "Full Board Plus" },
      { value: "All Inclusive Light", text: "All Inclusive Light" },
      { value: "All Inclusive Plus", text: "All Inclusive Plus" },
      { value: "All Inclusive Ultra", text: "All Inclusive Ultra" },
    ],
    hotelCharacteristics: [
      "charming",
      "colonial style",
      "elegant",
      "cosy",
      "eco-friendly management",
      "family-friendly",
      "fully renovated",
      "furnished in the local style",
      "ideal for couples",
      "in an Art Nouveau building",
      "individually furnished",
      "luxurious",
      "mediterranean",
      "modern",
      "newly built",
      "simple",
      "comfortable",
      "exclusive",
      "extravagant",
      "friendly",
      "generously designed",
      "homely atmosphere",
      "partly renovated",
      "pleasant",
      "popular",
      "popular among young guests",
      "premium middle class",
      "tasteful",
      "traditional",
      "vast",
      "stylish",
    ],
    outdoorCharacteristics: [
      "Mediterranean",
      "pleasant",
      "sunset view",
      "terraced",
      "tropical",
      "well kept",
      "barefoot island",
    ],
    outdoorEquipment: [
      "BBQ area",
      "boma",
      "bonfire site",
      "courtyard",
      "garden",
      "nudist terrace",
      "palm trees",
      "panoramic roof terrace",
      "park",
      "picnic area",
      "sun terrace",
      "sunbathing lawn",
      "swimming pond",
      "whirlpool",
      "Sky bar",
      "Camping site",
      "Outdoor furniture",
      "has Golf fields",
      "Roof lounge",
    ],
    hotelFacilityServices: [
      "ATM",
      "Ampitheatre",
      "TV Area/corner",
      "TV room",
      "amusement arcade",
      "bank/money exchange",
      "bike storage room",
      "boutique",
      "breakfast room",
      "business centre",
      "casino",
      "electric cars charging station",
      "cinema",
      "conference room(s)",
      "conservatory",
      "den with swiss pine panelling",
      "dining room",
      "fireplace room",
      "hairdresser",
      "jewelary",
      "launderette",
      "library",
      "lounge",
      "luggage room",
      "mini market",
      "partour",
      "pastry shop",
      "reading corner",
      "shisha corner",
      "shop(s)",
      "ski boots drying system",
      "ski storage room",
      "smoking room",
      "souvonir shop",
      "golf equipment storage room",
      "theatre",
      "vending machine",
      "wedding chapel",
    ],
    hotelCreditCards: [
      "Visa",
      "Mastercard",
      "Diners",
      "Amex",
      "American express",
      "All major credit cards",
    ],
    foodSpecialsTypes: [
      "afternoon tea included",
      "farmers buffet",
      "side dishes buffet",
      "organic food",
      "bread service for additional charge",
      "dessert buffet",
      "dietary food",
      "farmers buffet on occasion",
      "desert buffet on occasion",
      "gala dinner on occasion",
      "BBQ night on occasion",
      "show cooking on occasion",
      "themed buffet on occasion",
      "gluten free meals",
      "gluten free meals (on request)",
      "BBQ night",
      "afternoon coffee included",
      "afternoon coffee/cake included",
      "free of lactose",
      "free of lactose (on request)",
      "packed lunch",
      "lunch snack",
      "salad buffet with dinner",
      "sashimi corner",
      "sushi bar",
      "salad buffet for lunch",
      "show cooking",
      "themed buffet",
      "vegan",
      "vegetarian",
      "healthy section",
      "appetiser buffet",
      "ayurveda",
    ],
    hotelBreakfastTypes: [
      "a la carte",
      "American",
      "Buffet",
      "continental",
      "English",
      "served in the room",
      "set menu or buffet",
    ],
    hotelLunchTypes: [
      "a la carte",
      "Buffet",
      "choice of 2-course meals",
      "choice of 3-course meals",
      "choice of 4-course meals",
      "choice of 5-course meals",
      "credit of speciallity restaurant",
      "choice of meals",
      "lunch box",
      "light lunch",
      "set meal",
      "set menu or buffet",
      "snack",
      "table d hote",
    ],
    hotelDinnerTypes: [
      "a la carte",
      "Buffet",
      "choice of 2-course meals",
      "choice of 3-course meals",
      "choice of 4-course meals",
      "choice of 5-course meals",
      "credit of speciallity restaurant",
      "choice of meals",
      "lunch box",
      "light lunch",
      "set meal",
      "set menu or buffet",
      "snack",
      "table d hote",
    ],
    allInclusiveDrinkTypes: [
      "Selected local alcoholic drinks",
      "Selected non-alcoholic drinks",
      "Selected international alcoholic drinks",
      "Selected international non-alcoholic drinks",
      "drinks on the all inclusive menu",
    ],
    aISnacksTypes: [
      "Mixed nuts",
      "Pizza slices",
      "Bakeries",
      "Cheese",
      "Croissant",
      "Dates",
      "Dried fruits",
      "Hummus/Dip",
      "Olives",
      "Pop-corn",
    ],
    aISpecialServices: [
      "BBQ",
      "Mandatory wearing All Inclusive wristband",
      "Beach party",
      "Breakfast in room",
      "Cinema or Open-air Cinema",
      "Cocktail mixing class",
      "Complimentary room service",
      "Dine around",
      "Discount on spa treatment",
      "Drinks at the beach",
      "Drinks at the nightclub",
      "Fruit basket in the room",
      "Fruit service at the beach",
      "Fruit service at the pool",
      "Late check-out",
      "Library access",
      "Open air disco",
      "Shisha smoking",
      "Slide show",
    ],
    hotelChildrenEntertainment: [
      "academy",
      "autoscooter",
      "childcare",
      "children's farm",
      "children's entertainment",
      "courses for children",
      "games room",
      "gaming machine(s)",
      "handicrafts",
      "indoor play world",
      "kids make-over",
      "kids safari",
      "kids show",
      "mini disco",
      "playstation",
      "pool party",
      "sports tournaments",
      "wannabe activity",
      "Wii",
    ],
    hotelChildrenOtherServices: [
      "baby bathtub",
      "baby changing room",
      "baby monitor",
      "baby pool",
      "bottle warmer",
      "bouncy castle",
      "children bike rental",
      "children bathrobes",
      "children check-in",
      "children menu/buffet",
      "children spa",
      "climbing area",
      "game rental",
      "go-kart track",
      "helmet rental",
      "high chairs",
      "petting zoo",
      "pony riding",
      "pushchair rental",
      "stroller",
      "trampoline",
    ],
    daysOfTheWeek: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    roomTypes: [
      "3 bedroom",
      "3 bedroom comfort",
      "3 bedroom deluxe",
      "3 bedroom superior",
      "4 bedroom",
      "apartment",
      "apartment(1 bedeoom)",
      "apartment(2 bedroom)",
      "apartment(3 bedroom)",
      "apartment(4 bedroom)",
      "apartment(5 bedroom)",
      "apartment(6 bedroom)",
      "apartment deluxe",
      "apartment economy",
      "apartment single use",
      "apartment single with child",
      "apartment superior",
      "apartmentsuperior single use",
      "bungalow",
      "bungalow (1 bedroom)",
      "bungalow (2 bedroom)",
      "bungalow (3 bedroom)",
      "bungalow (4 bedroom)",
      "bungalow (5 bedroom)",
      "bungalow deluxe",
      "bungalow economy",
      "bungalow single use",
      "bungalow superior",
      "bungalow with child",
      "cabin",
      "chalet",
      "deluxe apartment (1 bedroom)",
      "deluxe apartment (2 bedroom)",
      "deluxe twin",
      "double room",
      "double room business",
      "double room club",
      "double room club single use",
      "double room comfort",
      "double room comfort single use",
      "double room deluxe",
      "double room deluxe single use",
      "double room economy",
      "double room executive",
      "double room homestay",
      "double room lady",
      "double room luxury",
      "double room premium",
      "double room premium single use",
      "double room separate beds",
      "double room single use with child",
      "double room superior",
      "double room superior single use",
      "double room villa",
      "double room with shared bathroom",
      "executive suite",
      "family accomomodation",
      "family bungalow",
      "family club room",
      "family deluxe room",
      "family maisonette",
      "family room",
      "family room (1 bedroom)",
      "family room (2 bedrooms)",
      "family room (3 bedrooms)",
      "family room economy",
      "family room superior",
      "family suite",
      "grand suite",
      "half double room",
      "half double room Home-stay",
      "holiday apartment",
      "holiday apartment (1 bedroom)",
      "holiday apartment (2 bedrooms)",
      "holiday apartment (3 bedrooms)",
      "holiday house",
      "house",
      "house (1 bedroom)",
      "house (2 bedrooms)",
      "house (3 bedrooms)",
      "house (4 bedrooms)",
      "juniorsuite",
      "juniorsuite deluxe",
      "juniorsuite prestige",
      "juniorsuite single use",
      "juniorsuite single use with child",
      "juniorsuite superior",
      "juniorsuite vip",
      "lodge",
      "luxury suite",
      "maisonette",
      "mobile home",
      "penthouse suite",
      "premium apartment (1 bedroom)",
      "premium apartment (2 bedrooms)",
      "promotion room",
      "royal club room",
      "royal suite",
      "shared room",
      "shared room Home-Stay",
      "shared room with shared bathroom",
      "single room",
      "single room comfort",
      "single room deluxe",
      "single room economy",
      "single room executive",
      "single room homestay",
      "single room royal club",
      "single room superior",
      "single room shared bathroom",
      "studio",
      "studio deluxe",
      "studio economy",
      "studio executive",
      "studio single use",
      "studio single with child",
      "studio superior",
      "studio superior single use",
      "suite",
      "suite 1 bedroom",
      "suite 2 bedrooms",
      "suite 3 bedrooms",
      "suite 4 bedrooms",
      "suite deluxe",
      "suite single use",
      "suite superior",
      "super-de-luxe",
      "superior apartment 1 bedroom",
      "superior apartment 2 bedrooms",
      "superior family room (1 bedroom)",
      "superior family room (2 bedrooms)",
      "superior twin",
      "tent",
      "tower room",
      "villa",
      "villa (1 bedroom)",
      "villa (2 bedrooms)",
      "villa (3 bedrooms)",
      "villa (4 bedrooms)",
      "villa (5 bedrooms)",
      "villa (6 bedrooms)",
      "villa deluxe",
      "villa junior suite",
      "villa super deluxe",
      "villa superior",
      "water bungalow",
      "water bungalow single use",
      "water villa",
    ],
    viewsOptions: [
      "Sea view",
      "Sea side",
      "Mountain view",
      "Pool side",
      "Lake view",
      "Side sea view",
      "Side sea side",
      "Side lake view",
      "Street view",
      "type A",
      "type B",
      "type C",
      "Main building",
      "Annex",
      "Balcony",
      "Honeymoon",
      "Roulette",
      "Air condition",
      "Lake side",
      "Quadruple",
      "run of the house",
      "triple",
      "1 additional bed",
      "2 additional bed",
      "Non Refundable",
      "Shared pool",
      "Low cost",
    ],
    saunasOptions: [
      "Finnish sauna",
      "Sanarium",
      "Aroma sauna",
      "Bio sauna",
      "Fresh air sauna",
      "Herbal sauna",
      "Infrared",
      "Log cabin sauna",
      "Panorama sauna",
      "Stone sauna",
      "Laconium",
    ],
    massagesOptions: [
      "Ayurveda massage",
      "LaStone therapy",
      "Thai massage",
      "Anti-cellullite massage",
      "Aroma massage",
      "Chocolate massage",
      "Classic massage",
      "Foot reflexology",
      "Lymphatic drainage",
      "Shiatsu",
      "Singing bowl massage",
      "Sports massage",
      "Therapeutic massage",
    ],
    medicalTreatmentOptions: [
      "Kneipp therapy",
      "Acupuncture",
      "Balneotherapy",
      "Chromotherapy",
      "Electrotherapy",
      "Hydrotherapy",
      "Lymphogenous treatment",
      "Oxygen therapy",
    ],
    medicalTreatmentPathOptions: [
      "Aroma blossom bath",
      "Buttermilk bath",
      "Carbonic-acid bath",
      "Cavitosonic bath",
      "Cleopatra bath",
      "Evening primrose oil bath",
      "Exercise pool",
      "Hay bath",
      "Herbal bath",
      "Inhalation bath",
      "Iodine bath",
      "Mineral bath",
      "Multi-jet bath",
      "Oak bark bath",
      "Orange blossom bath",
      "Oxygen bath",
      "Peat bath",
      "Salt-water spa",
      "Sea salt pool",
      "Stone oil bath",
      "Sulphur bath",
      "Thermal bath",
    ],
    wellnessBeautyTreatmentOptions: [
      "Dermalife treatment",
      "Thalgomince body wrap",
      "Anti-ageing",
      "Aroma therapy",
      "Ayurveda therapy",
      "Cellulite treatment",
      "Cryotonic",
      "Facials",
      "Fango",
      "Full-body detox",
      "Hair removal",
      "Healing water cure",
      "Inhalation",
      "Magnetic therapy",
      "Manicure",
      "Masks",
      "Packs",
      "Paraffin treatment",
      "Pedicure",
      "Peeling",
      "Thalassotherapy",
    ],
    maintenanceTypes: [
      "Beach construction site",
      "Closure of outdoor pool",
      "Closure of spa area",
      "Complete hotel closure",
      "Indoor pool closure",
      "Indoor pool renovation",
      "Lobby renovation",
      "Neighboring construction site",
      "Outdoor pool renovation",
      "Renovation of children facility",
      "Renovation of exterior facade",
      "Renovation of fitness centre",
      "Renovation of outdoor area",
      "Renovation of public areas",
      "Restaurant closure",
      "Restaurant renovation",
      "Road construction near hotel",
      "Rooms renovation",
      "Spa renovation",
      "Tennis court closure",
    ],
    contractTerms: [
      { value: "F", text: "Full partnership" },
      { value: "N", text: "Non contracted affiliate" },
      { value: "C", text: "Customer contract" },
    ],
    contractPhotoOptions: [
      { value: "A", text: "Allowed" },
      { value: "N", text: "Not allowed" },
      { value: "E", text: "Only with approval by e-mail" },
    ],
    contractSpecialAllotment: [
      { value: "S", text: "Special stop-sale allotment" },
      { value: "G", text: "General accommodations stop-sale" },
    ],
    contractStatus: [
      { value: "D", text: "Draft" },
      { value: "P", text: "Pending" },
      { value: "C", text: "Changed" },
      { value: "R", text: "Rejected" },
      { value: "X", text: "Canceled" },
      { value: "A", text: "Accepted" },
    ],
    contractBoolean: [
      { value: "Y", text: "Yes" },
      { value: "N", text: "No" },
      { value: "O", text: "Only with approval by e-mail" },
    ],
  },

  getters: {
    getdaysOfTheWeek(state) {
      return state.daysOfTheWeek;
    },
    getLocationEnvironment(state) {
      return state.locationEnvironment;
    },
    getAroundHotel(state) {
      return state.aroundHotel;
    },
    getBeachCharacteristics(state) {
      return state.beachCharacteristics;
    },
    getMoreBeachInfo(state) {
      return state.moreBeachInfo;
    },
    getBeachInformation(state) {
      return state.beachInformation;
    },
    getBeachPathType(state) {
      return state.beachPathType;
    },
    getDistanceTypes(state) {
      return state.distanceTypes;
    },
    getHotelCharacteristics(state) {
      return state.hotelCharacteristics;
    },
    getOutdoorCharacteristics(state) {
      return state.outdoorCharacteristics;
    },
    getHotelChildrenEntertainment(state) {
      return state.hotelChildrenEntertainment;
    },
    getHotelChildrenOtherServices(state) {
      return state.hotelChildrenOtherServices;
    },
    getOutdoorEquipment(state) {
      return state.outdoorEquipment;
    },
    getHotelFacilityServices(state) {
      return state.hotelFacilityServices;
    },
    getHotelCreditCards(state) {
      return state.hotelCreditCards;
    },
    getBoardsTypes(state) {
      return state.boardsAvailableOptions;
    },
    getBreakfastMealsTypes(state) {
      return state.hotelBreakfastTypes;
    },
    getLunchMealsTypes(state) {
      return state.hotelLunchTypes;
    },
    getDinnerMealsTypes(state) {
      return state.hotelDinnerTypes;
    },
    getSpecialMealsTypes(state) {
      return state.foodSpecialsTypes;
    },
    getAISnacksTypes(state) {
      return state.aISnacksTypes;
    },
    getAIDrinksTypes(state) {
      return state.allInclusiveDrinkTypes;
    },
    getAISpecialServices(state) {
      return state.aISpecialServices;
    },
    getRoomtypes(state) {
      return state.roomTypes;
    },
    getViewsOptions(state) {
      return state.viewsOptions;
    },
    getSaunasOptions(state) {
      return state.saunasOptions;
    },
    getMassagesOptions(state) {
      return state.massagesOptions;
    },
    getMedicalTreatmentOptions(state) {
      return state.medicalTreatmentOptions;
    },
    getMedicalTreatmentPathOptions(state) {
      return state.medicalTreatmentPathOptions;
    },
    getWellnessBeautyTreatmentOptions(state) {
      return state.wellnessBeautyTreatmentOptions;
    },
    getMaintenanceTypes(state) {
      return state.maintenanceTypes;
    },
    getContractTerms(state) {
      return state.contractTerms;
    },
    getContractPhotoOptions(state) {
      return state.contractPhotoOptions;
    },
    getContractSpecialAllotment(state) {
      return state.contractSpecialAllotment;
    },
    getContractStatus(state) {
      return state.contractStatus;
    },
    getContractBoolean(state) {
      return state.contractBoolean;
    },
  },
};
