import axios from "axios";

export default {
  namespaced: true,
  state: {
    property: {
      id: 0,
      hotel: 0,
      sportsAvailable: false,
      aerobicsAvailable: false,
      aerobicsLocalSupplier: false,
      aerobicsCharges: null,
      aerobicsClassAvailable: false,
      boulderWallAvailable: false,
      boulderWallLocalSupplier: false,
      boulderWallCharges: null,
      boulderWallClass: false,
      fitnessCentreAvailable: false,
      fitnessCentreLocalSupplier: false,
      fitnessCentreCharges: null,
      fitnessCentreSize: 0,
      fitnessCentreAgeFrom: null,
      fitnessCentreInWellness: false,
      fitnessCentreClassAvailable: false,
      gymAvailable: false,
      gymLocalSupplier: false,
      gymCharges: null,
      gymSize: null,
      gymAgeFrom: null,
      gymInWellness: false,
      gymTrainingAvailable: false,
      gymnasticsAvailable: false,
      gymnasticsLocalSupplier: false,
      gymnasticsCharges: null,
      climbingWallAvailable: false,
      climbingWallLocalSupplier: false,
      climbingWallCharges: null,
      climbingWallClass: false,
      mountainBikeTour: false,
      mountainBikeTourLocalSupplier: false,
      mountainBikeTourCharges: null,
      mountainBikeRental: false,
      mountainBikeRentalLocalSupplier: false,
      mountainBikeRentalCharges: null,
      nordicWalking: false,
      nordicWalkingLocalSupplier: false,
      nordicWalkingCharges: null,
      nordicWalkingTraining: false,
      nordicWalkingEquipRental: false,
      nordicWalkingEquipCharges: null,
      openAirFitness: false,
      openAirFitnessLocalSupplier: false,
      openAirFitnessCharges: null,
      stepAerobics: false,
      stepAerobicsLocalSupplier: false,
      stepAerobicsCharges: null,
      stepAerobicsTraining: false,
      danceClass: false,
      danceClassLocalSupplier: false,
      danceClassCharges: null,
      fitnessClass: false,
      fitnessClassLocalSupplier: false,
      fitnessClassCharges: null,
      waterSportsActivitiesAvailable: false,
      aquaGymnastics: false,
      aquaGymnasticsLocalSupplier: false,
      aquaGymnasticsCharges: null,
      severalMotorisedSports: false,
      severalMotorisedSportsLocalSupplier: false,
      severalMotorisedSportsCharges: null,
      standUpPaddling: false,
      standUpPaddlingLocalSupplier: false,
      standUpPaddlingCharges: null,
      waterPolo: false,
      waterPoloLocalSupplier: false,
      waterPoloCharges: null,
      bananaBoat: false,
      bananaBoatLocalSupplier: false,
      bananaBoatCharges: null,
      boatTrip: false,
      boatTripLocalSupplier: false,
      boatTripCharges: null,
      boogieBoards: false,
      boogieBoardsLocalSupplier: false,
      boogieBoardsCharges: null,
      canoe: false,
      canoeLocalSupplier: false,
      canoeCharges: null,
      catamaran: false,
      catamaranLocalSupplier: false,
      catamaranCharges: null,
      bCooling: false,
      bCoolingLocalSupplier: false,
      bCoolingCharges: null,
      angling: false,
      anglingLocalSupplier: false,
      anglingCharges: null,
      glassBoatBottom: false,
      glassBoatBottomLocalSupplier: false,
      glassBoatBottomCharges: null,
      jetSkii: false,
      jetSkiiLocalSupplier: false,
      jetSkiiCharges: null,
      kayak: false,
      kayakLocalSupplier: false,
      kayakCharges: null,
      kiteSurfing: false,
      kiteSurfingLocalSupplier: false,
      kiteSurfingCharges: null,
      motoBoat: false,
      motoBoatLocalSupplier: false,
      motoBoatCharges: null,
      localOpenAirPool: false,
      localOpenAirPoolLocalSupplier: false,
      localOpenAirPoolCharges: null,
      parasailing: false,
      parasailingLocalSupplier: false,
      parasailingCharges: null,
      pedalo: false,
      pedaloLocalSupplier: false,
      pedaloCharges: null,
      rafting: false,
      raftingLocalSupplier: false,
      raftingCharges: null,
      rowBoat: false,
      rowBoatLocalSupplier: false,
      rowBoatCharges: null,
      sailing: false,
      sailingLocalSupplier: false,
      sailingCharges: null,
      seaAngling: false,
      seaAnglingLocalSupplier: false,
      seaAnglingCharges: null,
      snorkeling: false,
      snorkelingLocalSupplier: false,
      snorkelingCharges: null,
      surfing: false,
      surfingLocalSupplier: false,
      surfingCharges: null,
      coolingTasterCourse: false,
      coolingTasterCourseLocalSupplier: false,
      coolingTasterCourseCharges: null,
      wakeBoard: false,
      wakeBoardLocalSupplier: false,
      wakeBoardCharges: null,
      waterSki: false,
      waterSkiLocalSupplier: false,
      waterSkiCharges: null,
      windSurfing: false,
      windSurfingLocalSupplier: false,
      windSurfingCharges: null,
      ballSportsActivitiesAvailable: false,
      badminton: false,
      badmintonLocalSupplier: false,
      badmintonCharges: null,
      basketBall: false,
      basketBallLocalSupplier: false,
      basketBallCharges: null,
      beachVolleyBall: false,
      beachVolleyBallLocalSupplier: false,
      beachVolleyBallCharges: null,
      beachSoccer: false,
      beachSoccerLocalSupplier: false,
      beachSoccerCharges: null,
      billiard: false,
      billiardLocalSupplier: false,
      billiardCharges: null,
      barce: false,
      barceLocalSupplier: false,
      barceCharges: null,
      bowling: false,
      bowlingLocalSupplier: false,
      bowlingCharges: null,
      cricket: false,
      cricketLocalSupplier: false,
      cricketCharges: null,
      soccer: false,
      soccerLocalSupplier: false,
      soccerCharges: null,
      golf: false,
      golfLocalSupplier: false,
      golfCharges: null,
      skittles: false,
      skittlesLocalSupplier: false,
      skittlesCharges: null,
      miniGolf: false,
      miniGolfLocalSupplier: false,
      miniGolfCharges: null,
      paddleTennis: false,
      paddleTennisLocalSupplier: false,
      paddleTennisCharges: null,
      squash: false,
      squashLocalSupplier: false,
      squashCharges: null,
      tennis: false,
      tennisLocalSupplier: false,
      tennisCharges: null,
      tableTennis: false,
      tableTennisLocalSupplier: false,
      tableTennisCharges: null,
      volleyBall: false,
      volleyBallLocalSupplier: false,
      volleyBallCharges: null,
      winterSportsActivitiesAvailable: false,
      alpineSkiing: false,
      alpineSkiingLocalSupplier: false,
      alpineSkiingCharges: null,
      crossCountrySkiing: false,
      crossCountrySkiingLocalSupplier: false,
      crossCountrySkiingCharges: null,
      snowBoarding: false,
      snowBoardingLocalSupplier: false,
      snowBoardingCharges: null,
      tobogganing: false,
      tobogganingLocalSupplier: false,
      tobogganingCharges: null,
      otherSportsActivitiesAvailable: false,
      airHockey: false,
      airHockeyLocalSupplier: false,
      airHockeyCharges: null,
      airRifleShooting: false,
      airRifleShootingLocalSupplier: false,
      airRifleShootingCharges: null,
      archery: false,
      archeryLocalSupplier: false,
      archeryCharges: null,
      ballooning: false,
      ballooningLocalSupplier: false,
      ballooningCharges: null,
      bikeRental: false,
      bikeRentalLocalSupplier: false,
      bikeRentalCharges: null,
      camelRiding: false,
      camelRidingLocalSupplier: false,
      camelRidingCharges: null,
      carriageRides: false,
      carriageRidesLocalSupplier: false,
      carriageRidesCharges: null,
      climbing: false,
      climbingLocalSupplier: false,
      climbingCharges: null,
      crossBowShooting: false,
      crossBowShootingLocalSupplier: false,
      crossBowShootingCharges: null,
      darts: false,
      dartsLocalSupplier: false,
      dartsCharges: null,
      eBikeRental: false,
      eBikeRentalLocalSupplier: false,
      eBikeRentalCharges: null,
      gameTown: false,
      gameTownLocalSupplier: false,
      gameTownCharges: null,
      geoCoaching: false,
      geoCoachingLocalSupplier: false,
      geoCoachingCharges: null,
      giantChess: false,
      giantChessLocalSupplier: false,
      giantChessCharges: null,
      guidedHikes: false,
      guidedHikesLocalSupplier: false,
      guidedHikesCharges: null,
      horseRiding: false,
      horseRidingLocalSupplier: false,
      horseRidingCharges: null,
      laserBall: false,
      laserBallLocalSupplier: false,
      laserBallCharges: null,
      multiFunctionalSpace: false,
      multiFunctionalSpaceLocalSupplier: false,
      multiFunctionalSpaceCharges: null,
      paintBall: false,
      paintBallLocalSupplier: false,
      paintBallCharges: null,
      paragliding: false,
      paraglidingLocalSupplier: false,
      paraglidingCharges: null,
      pilates: false,
      pilatesLocalSupplier: false,
      pilatesCharges: null,
      quadRental: false,
      quadRentalLocalSupplier: false,
      quadRentalCharges: null,
      segwayRental: false,
      segwayRentalLocalSupplier: false,
      segwayRentalCharges: null,
      shuffleBoard: false,
      shuffleBoardLocalSupplier: false,
      shuffleBoardCharges: null,
      spinning: false,
      spinningLocalSupplier: false,
      spinningCharges: null,
      summerToboGganing: false,
      summerToboGganingLocalSupplier: false,
      summerToboGganingCharges: null,
      tableFootBall: false,
      tableFootBallLocalSupplier: false,
      tableFootBallCharges: null,
      towerJump: false,
      towerJumpLocalSupplier: false,
      towerJumpCharges: null,
      yogaClass: false,
      yogaClassLocalSupplier: false,
      yogaClassCharges: null,
      zipWire: false,
      zipWireLocalSupplier: false,
      zipWireCharges: null,
      steamBath: false,
      steamBathAdmissionFrom: null,
      steamBathCharges: null,
      indoorSwimmingPool: false,
      indoorSwimmingPoolCharges: null,
      indoorSwimmingPoolIsSeasonal: false,
      indoorSwimmingPoolCheck: false,
      indoorSwimmingPoolFrom: null,
      indoorSwimmingPoolTo: null,
      saunas: false,
      saunasCount: null,
      saunasCharges: null,
      saunasTypes: [],
      massages: false,
      massagesTypes: [],
      medicalTreatment: false,
      medicalTreatmentTypes: [],
      medicalTreatmentBathes: [],
      beautyTreatment: false,
      wellnessBeautyTreatment: [],
    },
    errors: [],
  },
  mutations: {
    updateProperty(state, newProperty) {
      state.property = newProperty;
    },
    updateErrors(state, newInfo) {
      /* console.log("commit here", newInfo); */
      state.errors = newInfo;
    },
  },
  actions: {
    validate(context, newInfo) {
      context.commit("updateErrors", newInfo);
    },
    postInfo(context, newInfo) {
      axios.defaults.headers.common.Authorization = `Token ${context.rootState.user.token}`;
      /* console.log(`Token is ${context.rootState.user.token}`); */
      /* console.log(newInfo); */
      const requestMethod = newInfo.id ? "put" : "post";
      const requestUrl = newInfo.id
        ? `http://127.0.0.1:8000/api/facts/sports-wellness/update/${newInfo.id}/`
        : "http://127.0.0.1:8000/api/facts/sports-wellness/create/";
      return new Promise((resolve, reject) => {
        axios({
          method: requestMethod,
          url: requestUrl,
          data: newInfo,
        })
          .then((response) => {
            /* console.log("response is", response.data); */
            const savedInfo = {
              id: response.data.hotel,
              hotel: response.data.hotel,
              sportsAvailable: response.data.sports_available,
              aerobicsAvailable: response.data.aerobics_available,
              aerobicsLocalSupplier: response.data.aerobics_local_supplier,
              aerobicsCharges: response.data.aerobics_charges,
              aerobicsClassAvailable: response.data.aerobics_class_available,
              boulderWallAvailable: response.data.boulder_wall_available,
              boulderWallLocalSupplier: response.data.boulder_wall_local_supplier,
              boulderWallCharges: response.data.boulder_wall_charges,
              boulderWallClass: response.data.boulder_wall_class,
              fitnessCentreAvailable: response.data.fitness_centre_available,
              fitnessCentreLocalSupplier: response.data.fitness_centre_local_supplier,
              fitnessCentreCharges: response.data.fitness_centre_charges,
              fitnessCentreSize: response.data.fitness_centre_size,
              fitnessCentreAgeFrom: response.data.fitness_centre_age_from,
              fitnessCentreInWellness: response.data.fitness_centre_in_wellness,
              fitnessCentreClassAvailable: response.data.fitness_centre_class_available,
              gymAvailable: response.data.gym_available,
              gymLocalSupplier: response.data.gym_local_supplier,
              gymCharges: response.data.gym_charges,
              gymSize: response.data.gym_size,
              gymAgeFrom: response.data.gym_age_from,
              gymInWellness: response.data.gym_in_wellness,
              gymTrainingAvailable: response.data.gym_training_available,
              gymnasticsAvailable: response.data.gymnastics_available,
              gymnasticsLocalSupplier: response.data.gymnastics_local_supplier,
              gymnasticsCharges: response.data.gymnastics_charges,
              climbingWallAvailable: response.data.climbing_wall_available,
              climbingWallLocalSupplier: response.data.climbing_wall_local_supplier,
              climbingWallCharges: response.data.climbing_wall_charges,
              climbingWallClass: response.data.climbing_wall_class,
              mountainBikeTour: response.data.mountain_bike_tour,
              mountainBikeTourLocalSupplier: response.data.mountain_bike_tour_local_supplier,
              mountainBikeTourCharges: response.data.mountain_bike_tour_charges,
              mountainBikeRental: response.data.mountain_bike_rental,
              mountainBikeRentalLocalSupplier: response.data.mountain_bike_rental_local_supplier,
              mountainBikeRentalCharges: response.data.mountain_bike_rental_charges,
              nordicWalking: response.data.nordic_walking,
              nordicWalkingLocalSupplier: response.data.nordic_walking_local_supplier,
              nordicWalkingCharges: response.data.nordic_walking_charges,
              nordicWalkingTraining: response.data.nordic_walking_training,
              nordicWalkingEquipRental: response.data.nordic_walking_equip_rental,
              nordicWalkingEquipCharges: response.data.nordic_walking_equip_charges,
              openAirFitness: response.data.open_air_fitness,
              openAirFitnessLocalSupplier: response.data.open_air_fitness_local_supplier,
              openAirFitnessCharges: response.data.open_air_fitness_charges,
              stepAerobics: response.data.step_aerobics,
              stepAerobicsLocalSupplier: response.data.step_aerobics_local_supplier,
              stepAerobicsCharges: response.data.step_aerobics_charges,
              stepAerobicsTraining: response.data.step_aerobics_training,
              danceClass: response.data.dance_class,
              danceClassLocalSupplier: response.data.dance_class_local_supplier,
              danceClassCharges: response.data.dance_class_charges,
              fitnessClass: response.data.fitness_class,
              fitnessClassLocalSupplier: response.data.fitness_class_local_supplier,
              fitnessClassCharges: response.data.fitness_class_charges,
              waterSportsActivitiesAvailable: response.data.water_sports_activities_available,
              aquaGymnastics: response.data.aqua_gymnastics,
              aquaGymnasticsLocalSupplier: response.data.aqua_gymnastics_local_supplier,
              aquaGymnasticsCharges: response.data.aqua_gymnastics_charges,
              severalMotorisedSports: response.data.several_motorised_sports,
              severalMotorisedSportsLocalSupplier:
                response.data.several_motorised_sports_local_supplier,
              severalMotorisedSportsCharges: response.data.several_motorised_sports_charges,
              standUpPaddling: response.data.stand_up_paddling,
              standUpPaddlingLocalSupplier: response.data.stand_up_paddling_local_supplier,
              standUpPaddlingCharges: response.data.stand_up_paddling_charges,
              waterPolo: response.data.water_polo,
              waterPoloLocalSupplier: response.data.water_polo_local_supplier,
              waterPoloCharges: response.data.water_polo_charges,
              bananaBoat: response.data.banana_boat,
              bananaBoatLocalSupplier: response.data.banana_boat_local_supplier,
              bananaBoatCharges: response.data.banana_boat_charges,
              boatTrip: response.data.boat_trip,
              boatTripLocalSupplier: response.data.boat_trip_local_supplier,
              boatTripCharges: response.data.boat_trip_charges,
              boogieBoards: response.data.boogie_boards,
              boogieBoardsLocalSupplier: response.data.boogie_boards_local_supplier,
              boogieBoardsCharges: response.data.boogie_boards_charges,
              canoe: response.data.canoe,
              canoeLocalSupplier: response.data.canoe_local_supplier,
              canoeCharges: response.data.canoe_charges,
              catamaran: response.data.catamaran,
              catamaranLocalSupplier: response.data.catamaran_local_supplier,
              catamaranCharges: response.data.catamaran_charges,
              bCooling: response.data.b_cooling,
              bCoolingLocalSupplier: response.data.b_cooling_local_supplier,
              bCoolingCharges: response.data.b_cooling_charges,
              angling: response.data.angling,
              anglingLocalSupplier: response.data.angling_local_supplier,
              anglingCharges: response.data.angling_charges,
              glassBoatBottom: response.data.glass_boat_bottom,
              glassBoatBottomLocalSupplier: response.data.glass_boat_bottom_local_supplier,
              glassBoatBottomCharges: response.data.glass_boat_bottom_charges,
              jetSkii: response.data.jet_skii,
              jetSkiiLocalSupplier: response.data.jet_skii_local_supplier,
              jetSkiiCharges: response.data.jet_skii_charges,
              kayak: response.data.kayak,
              kayakLocalSupplier: response.data.kayak_local_supplier,
              kayakCharges: response.data.kayak_charges,
              kiteSurfing: response.data.kite_surfing,
              kiteSurfingLocalSupplier: response.data.kite_surfing_local_supplier,
              kiteSurfingCharges: response.data.kite_surfing_charges,
              motoBoat: response.data.moto_boat,
              motoBoatLocalSupplier: response.data.moto_boat_local_supplier,
              motoBoatCharges: response.data.moto_boat_charges,
              localOpenAirPool: response.data.local_open_air_pool,
              localOpenAirPoolLocalSupplier: response.data.local_open_air_pool_local_supplier,
              localOpenAirPoolCharges: response.data.local_open_air_pool_charges,
              parasailing: response.data.parasailing,
              parasailingLocalSupplier: response.data.parasailing_local_supplier,
              parasailingCharges: response.data.parasailing_charges,
              pedalo: response.data.pedalo,
              pedaloLocalSupplier: response.data.pedalo_local_supplier,
              pedaloCharges: response.data.pedalo_charges,
              rafting: response.data.rafting,
              raftingLocalSupplier: response.data.rafting_local_supplier,
              raftingCharges: response.data.rafting_charges,
              rowBoat: response.data.row_boat,
              rowBoatLocalSupplier: response.data.row_boat_local_supplier,
              rowBoatCharges: response.data.row_boat_charges,
              sailing: response.data.sailing,
              sailingLocalSupplier: response.data.sailing_local_supplier,
              sailingCharges: response.data.sailing_charges,
              seaAngling: response.data.sea_angling,
              seaAnglingLocalSupplier: response.data.sea_angling_local_supplier,
              seaAnglingCharges: response.data.sea_angling_charges,
              snorkeling: response.data.snorkeling,
              snorkelingLocalSupplier: response.data.snorkeling_local_supplier,
              snorkelingCharges: response.data.snorkeling_charges,
              surfing: response.data.surfing,
              surfingLocalSupplier: response.data.surfing_local_supplier,
              surfingCharges: response.data.surfing_charges,
              coolingTasterCourse: response.data.cooling_taster_course,
              coolingTasterCourseLocalSupplier: response.data.cooling_taster_course_local_supplier,
              coolingTasterCourseCharges: response.data.cooling_taster_course_charges,
              wakeBoard: response.data.wake_board,
              wakeBoardLocalSupplier: response.data.wake_board_local_supplier,
              wakeBoardCharges: response.data.wake_board_charges,
              waterSki: response.data.water_ski,
              waterSkiLocalSupplier: response.data.water_ski_local_supplier,
              waterSkiCharges: response.data.water_ski_charges,
              windSurfing: response.data.wind_surfing,
              windSurfingLocalSupplier: response.data.wind_surfing_local_supplier,
              windSurfingCharges: response.data.wind_surfing_charges,
              ballSportsActivitiesAvailable: response.data.ball_sports_activities_available,
              badminton: response.data.badminton,
              badmintonLocalSupplier: response.data.badminton_local_supplier,
              badmintonCharges: response.data.badminton_charges,
              basketBall: response.data.basket_ball,
              basketBallLocalSupplier: response.data.basket_ball_local_supplier,
              basketBallCharges: response.data.basket_ball_charges,
              beachVolleyBall: response.data.beach_volley_ball,
              beachVolleyBallLocalSupplier: response.data.beach_volley_ball_local_supplier,
              beachVolleyBallCharges: response.data.beach_volley_ball_charges,
              beachSoccer: response.data.beach_soccer,
              beachSoccerLocalSupplier: response.data.beach_soccer_local_supplier,
              beachSoccerCharges: response.data.beach_soccer_charges,
              billiard: response.data.billiard,
              billiardLocalSupplier: response.data.billiard_local_supplier,
              billiardCharges: response.data.billiard_charges,
              barce: response.data.barce,
              barceLocalSupplier: response.data.barce_local_supplier,
              barceCharges: response.data.barce_charges,
              bowling: response.data.bowling,
              bowlingLocalSupplier: response.data.bowling_local_supplier,
              bowlingCharges: response.data.bowling_charges,
              cricket: response.data.cricket,
              cricketLocalSupplier: response.data.cricket_local_supplier,
              cricketCharges: response.data.cricket_charges,
              soccer: response.data.soccer,
              soccerLocalSupplier: response.data.soccer_local_supplier,
              soccerCharges: response.data.soccer_charges,
              golf: response.data.golf,
              golfLocalSupplier: response.data.golf_local_supplier,
              golfCharges: response.data.golf_charges,
              skittles: response.data.skittles,
              skittlesLocalSupplier: response.data.skittles_local_supplier,
              skittlesCharges: response.data.skittles_charges,
              miniGolf: response.data.mini_golf,
              miniGolfLocalSupplier: response.data.mini_golf_local_supplier,
              miniGolfCharges: response.data.mini_golf_charges,
              paddleTennis: response.data.paddle_tennis,
              paddleTennisLocalSupplier: response.data.paddle_tennis_local_supplier,
              paddleTennisCharges: response.data.paddle_tennis_charges,
              squash: response.data.squash,
              squashLocalSupplier: response.data.squash_local_supplier,
              squashCharges: response.data.squash_charges,
              tennis: response.data.tennis,
              tennisLocalSupplier: response.data.tennis_local_supplier,
              tennisCharges: response.data.tennis_charges,
              tableTennis: response.data.table_tennis,
              tableTennisLocalSupplier: response.data.table_tennis_local_supplier,
              tableTennisCharges: response.data.table_tennis_charges,
              volleyBall: response.data.volley_ball,
              volleyBallLocalSupplier: response.data.volley_ball_local_supplier,
              volleyBallCharges: response.data.volley_ball_charges,
              winterSportsActivitiesAvailable: response.data.winter_sports_activities_available,
              alpineSkiing: response.data.alpine_skiing,
              alpineSkiingLocalSupplier: response.data.alpine_skiing_local_supplier,
              alpineSkiingCharges: response.data.alpine_skiing_charges,
              crossCountrySkiing: response.data.cross_country_skiing,
              crossCountrySkiingLocalSupplier: response.data.cross_country_skiing_local_supplier,
              crossCountrySkiingCharges: response.data.cross_country_skiing_charges,
              snowBoarding: response.data.snow_boarding,
              snowBoardingLocalSupplier: response.data.snow_boarding_local_supplier,
              snowBoardingCharges: response.data.snow_boarding_charges,
              tobogganing: response.data.tobogganing,
              tobogganingLocalSupplier: response.data.tobogganing_local_supplier,
              tobogganingCharges: response.data.tobogganing_charges,
              otherSportsActivitiesAvailable: response.data.other_sports_activities_available,
              airHockey: response.data.air_hockey,
              airHockeyLocalSupplier: response.data.air_hockey_local_supplier,
              airHockeyCharges: response.data.air_hockey_charges,
              airRifleShooting: response.data.air_rifle_shooting,
              airRifleShootingLocalSupplier: response.data.air_rifle_shooting_local_supplier,
              airRifleShootingCharges: response.data.air_rifle_shooting_charges,
              archery: response.data.archery,
              archeryLocalSupplier: response.data.archery_local_supplier,
              archeryCharges: response.data.archery_charges,
              ballooning: response.data.ballooning,
              ballooningLocalSupplier: response.data.ballooning_local_supplier,
              ballooningCharges: response.data.ballooning_charges,
              bikeRental: response.data.bike_rental,
              bikeRentalLocalSupplier: response.data.bike_rental_local_supplier,
              bikeRentalCharges: response.data.bike_rental_charges,
              camelRiding: response.data.camel_riding,
              camelRidingLocalSupplier: response.data.camel_riding_local_supplier,
              camelRidingCharges: response.data.camel_riding_charges,
              carriageRides: response.data.carriage_rides,
              carriageRidesLocalSupplier: response.data.carriage_rides_local_supplier,
              carriageRidesCharges: response.data.carriage_rides_charges,
              climbing: response.data.climbing,
              climbingLocalSupplier: response.data.climbing_local_supplier,
              climbingCharges: response.data.climbing_charges,
              crossBowShooting: response.data.cross_bow_shooting,
              crossBowShootingLocalSupplier: response.data.cross_bow_shooting_local_supplier,
              crossBowShootingCharges: response.data.cross_bow_shooting_charges,
              darts: response.data.darts,
              dartsLocalSupplier: response.data.darts_local_supplier,
              dartsCharges: response.data.darts_charges,
              eBikeRental: response.data.e_bike_rental,
              eBikeRentalLocalSupplier: response.data.e_bike_rental_local_supplier,
              eBikeRentalCharges: response.data.e_bike_rental_charges,
              gameTown: response.data.game_town,
              gameTownLocalSupplier: response.data.game_town_local_supplier,
              gameTownCharges: response.data.game_town_charges,
              geoCoaching: response.data.geo_coaching,
              geoCoachingLocalSupplier: response.data.geo_coaching_local_supplier,
              geoCoachingCharges: response.data.geo_coaching_charges,
              giantChess: response.data.giant_chess,
              giantChessLocalSupplier: response.data.giant_chess_local_supplier,
              giantChessCharges: response.data.giant_chess_charges,
              guidedHikes: response.data.guided_hikes,
              guidedHikesLocalSupplier: response.data.guided_hikes_local_supplier,
              guidedHikesCharges: response.data.guided_hikes_charges,
              horseRiding: response.data.horse_riding,
              horseRidingLocalSupplier: response.data.horse_riding_local_supplier,
              horseRidingCharges: response.data.horse_riding_charges,
              laserBall: response.data.laser_ball,
              laserBallLocalSupplier: response.data.laser_ball_local_supplier,
              laserBallCharges: response.data.laser_ball_charges,
              multiFunctionalSpace: response.data.multi_functional_space,
              multiFunctionalSpaceLocalSupplier:
                response.data.multi_functional_space_local_supplier,
              multiFunctionalSpaceCharges: response.data.multi_functional_space_charges,
              paintBall: response.data.paint_ball,
              paintBallLocalSupplier: response.data.paint_ball_local_supplier,
              paintBallCharges: response.data.paint_ball_charges,
              paragliding: response.data.paragliding,
              paraglidingLocalSupplier: response.data.paragliding_local_supplier,
              paraglidingCharges: response.data.paragliding_charges,
              pilates: response.data.pilates,
              pilatesLocalSupplier: response.data.pilates_local_supplier,
              pilatesCharges: response.data.pilates_charges,
              quadRental: response.data.quad_rental,
              quadRentalLocalSupplier: response.data.quad_rental_local_supplier,
              quadRentalCharges: response.data.quad_rental_charges,
              segwayRental: response.data.segway_rental,
              segwayRentalLocalSupplier: response.data.segway_rental_local_supplier,
              segwayRentalCharges: response.data.segway_rental_charges,
              shuffleBoard: response.data.shuffle_board,
              shuffleBoardLocalSupplier: response.data.shuffle_board_local_supplier,
              shuffleBoardCharges: response.data.shuffle_board_charges,
              spinning: response.data.spinning,
              spinningLocalSupplier: response.data.spinning_local_supplier,
              spinningCharges: response.data.spinning_charges,
              summerToboGganing: response.data.summer_tobo_gganing,
              summerToboGganingLocalSupplier: response.data.summer_tobo_gganing_local_supplier,
              summerToboGganingCharges: response.data.summer_tobo_gganing_charges,
              tableFootBall: response.data.table_foot_ball,
              tableFootBallLocalSupplier: response.data.table_foot_ball_local_supplier,
              tableFootBallCharges: response.data.table_foot_ball_charges,
              towerJump: response.data.tower_jump,
              towerJumpLocalSupplier: response.data.tower_jump_local_supplier,
              towerJumpCharges: response.data.tower_jump_charges,
              yogaClass: response.data.yoga_class,
              yogaClassLocalSupplier: response.data.yoga_class_local_supplier,
              yogaClassCharges: response.data.yoga_class_charges,
              zipWire: response.data.zip_wire,
              zipWireLocalSupplier: response.data.zip_wire_local_supplier,
              zipWireCharges: response.data.zip_wire_charges,
              steamBath: response.data.steam_bath,
              steamBathAdmissionFrom: response.data.steam_bath_admission_from,
              steamBathCharges: response.data.steam_bath_charges,
              indoorSwimmingPool: response.data.indoor_swimming_pool,
              indoorSwimmingPoolCharges: response.data.indoor_swimming_pool_charges,
              indoorSwimmingPoolIsSeasonal: response.data.indoor_swimming_pool_is_seasonal,
              indoorSwimmingPoolCheck: response.data.indoor_swimming_pool_check,
              indoorSwimmingPoolFrom: response.data.indoor_swimming_pool_from,
              indoorSwimmingPoolTo: response.data.indoor_swimming_pool_to,
              saunas: response.data.saunas,
              saunasCount: response.data.saunas_count,
              saunasCharges: response.data.saunas_charges,
              saunasTypes: response.data.saunas_types || [],
              massages: response.data.massages,
              massagesTypes: response.data.massages_types || [],
              medicalTreatment: response.data.medical_treatment,
              medicalTreatmentTypes: response.data.medical_treatment_types || [],
              medicalTreatmentBathes: response.data.medical_treatment_bathes || [],
              beautyTreatment: response.data.beauty_treatment,
              wellnessBeautyTreatment: response.data.wellness_beauty_treatment || [],
            };
            /* console.log("saved info:", savedInfo); */
            context.commit("updateProperty", savedInfo);
            resolve(savedInfo);
          })
          .catch((error) => {
            reject(error.response.data);
          });
      });
    },
    getInfo(context, infoId) {
      /* console.log("getting info data"); */
      axios.defaults.headers.common.Authorization = `Token ${context.rootState.user.token}`;
      return new Promise((resolve, reject) => {
        axios({
          method: "get",
          url: `http://127.0.0.1:8000/api/facts/sports-wellness/${infoId}/`,
        })
          .then((response) => {
            /* console.log(response); */
            const retrievedInfo = {
              id: response.data.hotel,
              hotel: response.data.hotel,
              sportsAvailable: response.data.sports_available,
              aerobicsAvailable: response.data.aerobics_available,
              aerobicsLocalSupplier: response.data.aerobics_local_supplier,
              aerobicsCharges: response.data.aerobics_charges || null,
              aerobicsClassAvailable: response.data.aerobics_class_available,
              boulderWallAvailable: response.data.boulder_wall_available,
              boulderWallLocalSupplier: response.data.boulder_wall_local_supplier,
              boulderWallCharges: response.data.boulder_wall_charges || null,
              boulderWallClass: response.data.boulder_wall_class,
              fitnessCentreAvailable: response.data.fitness_centre_available,
              fitnessCentreLocalSupplier: response.data.fitness_centre_local_supplier,
              fitnessCentreCharges: response.data.fitness_centre_charges || null,
              fitnessCentreSize: response.data.fitness_centre_size,
              fitnessCentreAgeFrom: response.data.fitness_centre_age_from,
              fitnessCentreInWellness: response.data.fitness_centre_in_wellness,
              fitnessCentreClassAvailable: response.data.fitness_centre_class_available,
              gymAvailable: response.data.gym_available,
              gymLocalSupplier: response.data.gym_local_supplier,
              gymCharges: response.data.gym_charges || null,
              gymSize: response.data.gym_size,
              gymAgeFrom: response.data.gym_age_from,
              gymInWellness: response.data.gym_in_wellness,
              gymTrainingAvailable: response.data.gym_training_available,
              gymnasticsAvailable: response.data.gymnastics_available,
              gymnasticsLocalSupplier: response.data.gymnastics_local_supplier,
              gymnasticsCharges: response.data.gymnastics_charges || null,
              climbingWallAvailable: response.data.climbing_wall_available,
              climbingWallLocalSupplier: response.data.climbing_wall_local_supplier,
              climbingWallCharges: response.data.climbing_wall_charges || null,
              climbingWallClass: response.data.climbing_wall_class,
              mountainBikeTour: response.data.mountain_bike_tour,
              mountainBikeTourLocalSupplier: response.data.mountain_bike_tour_local_supplier,
              mountainBikeTourCharges: response.data.mountain_bike_tour_charges || null,
              mountainBikeRental: response.data.mountain_bike_rental,
              mountainBikeRentalLocalSupplier: response.data.mountain_bike_rental_local_supplier,
              mountainBikeRentalCharges: response.data.mountain_bike_rental_charges || null,
              nordicWalking: response.data.nordic_walking,
              nordicWalkingLocalSupplier: response.data.nordic_walking_local_supplier,
              nordicWalkingCharges: response.data.nordic_walking_charges || null,
              nordicWalkingTraining: response.data.nordic_walking_training,
              nordicWalkingEquipRental: response.data.nordic_walking_equip_rental,
              nordicWalkingEquipCharges: response.data.nordic_walking_equip_charges || null,
              openAirFitness: response.data.open_air_fitness,
              openAirFitnessLocalSupplier: response.data.open_air_fitness_local_supplier,
              openAirFitnessCharges: response.data.open_air_fitness_charges || null,
              stepAerobics: response.data.step_aerobics,
              stepAerobicsLocalSupplier: response.data.step_aerobics_local_supplier,
              stepAerobicsCharges: response.data.step_aerobics_charges || null,
              stepAerobicsTraining: response.data.step_aerobics_training,
              danceClass: response.data.dance_class,
              danceClassLocalSupplier: response.data.dance_class_local_supplier,
              danceClassCharges: response.data.dance_class_charges || null,
              fitnessClass: response.data.fitness_class,
              fitnessClassLocalSupplier: response.data.fitness_class_local_supplier,
              fitnessClassCharges: response.data.fitness_class_charges || null,
              waterSportsActivitiesAvailable: response.data.water_sports_activities_available,
              aquaGymnastics: response.data.aqua_gymnastics,
              aquaGymnasticsLocalSupplier: response.data.aqua_gymnastics_local_supplier,
              aquaGymnasticsCharges: response.data.aqua_gymnastics_charges || null,
              severalMotorisedSports: response.data.several_motorised_sports,
              severalMotorisedSportsLocalSupplier:
                response.data.several_motorised_sports_local_supplier,
              severalMotorisedSportsCharges: response.data.several_motorised_sports_charges || null,
              standUpPaddling: response.data.stand_up_paddling,
              standUpPaddlingLocalSupplier: response.data.stand_up_paddling_local_supplier,
              standUpPaddlingCharges: response.data.stand_up_paddling_charges || null,
              waterPolo: response.data.water_polo,
              waterPoloLocalSupplier: response.data.water_polo_local_supplier,
              waterPoloCharges: response.data.water_polo_charges || null,
              bananaBoat: response.data.banana_boat,
              bananaBoatLocalSupplier: response.data.banana_boat_local_supplier,
              bananaBoatCharges: response.data.banana_boat_charges || null,
              boatTrip: response.data.boat_trip,
              boatTripLocalSupplier: response.data.boat_trip_local_supplier,
              boatTripCharges: response.data.boat_trip_charges || null,
              boogieBoards: response.data.boogie_boards,
              boogieBoardsLocalSupplier: response.data.boogie_boards_local_supplier,
              boogieBoardsCharges: response.data.boogie_boards_charges || null,
              canoe: response.data.canoe,
              canoeLocalSupplier: response.data.canoe_local_supplier,
              canoeCharges: response.data.canoe_charges || null,
              catamaran: response.data.catamaran,
              catamaranLocalSupplier: response.data.catamaran_local_supplier,
              catamaranCharges: response.data.catamaran_charges || null,
              bCooling: response.data.b_cooling,
              bCoolingLocalSupplier: response.data.b_cooling_local_supplier,
              bCoolingCharges: response.data.b_cooling_charges || null,
              angling: response.data.angling,
              anglingLocalSupplier: response.data.angling_local_supplier,
              anglingCharges: response.data.angling_charges || null,
              glassBoatBottom: response.data.glass_boat_bottom,
              glassBoatBottomLocalSupplier: response.data.glass_boat_bottom_local_supplier,
              glassBoatBottomCharges: response.data.glass_boat_bottom_charges || null,
              jetSkii: response.data.jet_skii,
              jetSkiiLocalSupplier: response.data.jet_skii_local_supplier,
              jetSkiiCharges: response.data.jet_skii_charges || null,
              kayak: response.data.kayak,
              kayakLocalSupplier: response.data.kayak_local_supplier,
              kayakCharges: response.data.kayak_charges || null,
              kiteSurfing: response.data.kite_surfing,
              kiteSurfingLocalSupplier: response.data.kite_surfing_local_supplier,
              kiteSurfingCharges: response.data.kite_surfing_charges || null,
              motoBoat: response.data.moto_boat,
              motoBoatLocalSupplier: response.data.moto_boat_local_supplier,
              motoBoatCharges: response.data.moto_boat_charges || null,
              localOpenAirPool: response.data.local_open_air_pool,
              localOpenAirPoolLocalSupplier: response.data.local_open_air_pool_local_supplier,
              localOpenAirPoolCharges: response.data.local_open_air_pool_charges || null,
              parasailing: response.data.parasailing,
              parasailingLocalSupplier: response.data.parasailing_local_supplier,
              parasailingCharges: response.data.parasailing_charges || null,
              pedalo: response.data.pedalo,
              pedaloLocalSupplier: response.data.pedalo_local_supplier,
              pedaloCharges: response.data.pedalo_charges || null,
              rafting: response.data.rafting,
              raftingLocalSupplier: response.data.rafting_local_supplier,
              raftingCharges: response.data.rafting_charges || null,
              rowBoat: response.data.row_boat,
              rowBoatLocalSupplier: response.data.row_boat_local_supplier,
              rowBoatCharges: response.data.row_boat_charges || null,
              sailing: response.data.sailing,
              sailingLocalSupplier: response.data.sailing_local_supplier,
              sailingCharges: response.data.sailing_charges || null,
              seaAngling: response.data.sea_angling,
              seaAnglingLocalSupplier: response.data.sea_angling_local_supplier,
              seaAnglingCharges: response.data.sea_angling_charges || null,
              snorkeling: response.data.snorkeling,
              snorkelingLocalSupplier: response.data.snorkeling_local_supplier,
              snorkelingCharges: response.data.snorkeling_charges || null,
              surfing: response.data.surfing,
              surfingLocalSupplier: response.data.surfing_local_supplier,
              surfingCharges: response.data.surfing_charges || null,
              coolingTasterCourse: response.data.cooling_taster_course,
              coolingTasterCourseLocalSupplier: response.data.cooling_taster_course_local_supplier,
              coolingTasterCourseCharges: response.data.cooling_taster_course_charges || null,
              wakeBoard: response.data.wake_board,
              wakeBoardLocalSupplier: response.data.wake_board_local_supplier,
              wakeBoardCharges: response.data.wake_board_charges || null,
              waterSki: response.data.water_ski,
              waterSkiLocalSupplier: response.data.water_ski_local_supplier,
              waterSkiCharges: response.data.water_ski_charges || null,
              windSurfing: response.data.wind_surfing,
              windSurfingLocalSupplier: response.data.wind_surfing_local_supplier,
              windSurfingCharges: response.data.wind_surfing_charges || null,
              ballSportsActivitiesAvailable: response.data.ball_sports_activities_available,
              badminton: response.data.badminton,
              badmintonLocalSupplier: response.data.badminton_local_supplier,
              badmintonCharges: response.data.badminton_charges || null,
              basketBall: response.data.basket_ball,
              basketBallLocalSupplier: response.data.basket_ball_local_supplier,
              basketBallCharges: response.data.basket_ball_charges || null,
              beachVolleyBall: response.data.beach_volley_ball,
              beachVolleyBallLocalSupplier: response.data.beach_volley_ball_local_supplier,
              beachVolleyBallCharges: response.data.beach_volley_ball_charges || null,
              beachSoccer: response.data.beach_soccer,
              beachSoccerLocalSupplier: response.data.beach_soccer_local_supplier,
              beachSoccerCharges: response.data.beach_soccer_charges || null,
              billiard: response.data.billiard,
              billiardLocalSupplier: response.data.billiard_local_supplier,
              billiardCharges: response.data.billiard_charges || null,
              barce: response.data.barce,
              barceLocalSupplier: response.data.barce_local_supplier,
              barceCharges: response.data.barce_charges || null,
              bowling: response.data.bowling,
              bowlingLocalSupplier: response.data.bowling_local_supplier,
              bowlingCharges: response.data.bowling_charges || null,
              cricket: response.data.cricket,
              cricketLocalSupplier: response.data.cricket_local_supplier,
              cricketCharges: response.data.cricket_charges || null,
              soccer: response.data.soccer,
              soccerLocalSupplier: response.data.soccer_local_supplier,
              soccerCharges: response.data.soccer_charges || null,
              golf: response.data.golf,
              golfLocalSupplier: response.data.golf_local_supplier,
              golfCharges: response.data.golf_charges || null,
              skittles: response.data.skittles,
              skittlesLocalSupplier: response.data.skittles_local_supplier,
              skittlesCharges: response.data.skittles_charges || null,
              miniGolf: response.data.mini_golf,
              miniGolfLocalSupplier: response.data.mini_golf_local_supplier,
              miniGolfCharges: response.data.mini_golf_charges || null,
              paddleTennis: response.data.paddle_tennis,
              paddleTennisLocalSupplier: response.data.paddle_tennis_local_supplier,
              paddleTennisCharges: response.data.paddle_tennis_charges || null,
              squash: response.data.squash,
              squashLocalSupplier: response.data.squash_local_supplier,
              squashCharges: response.data.squash_charges || null,
              tennis: response.data.tennis,
              tennisLocalSupplier: response.data.tennis_local_supplier,
              tennisCharges: response.data.tennis_charges || null,
              tableTennis: response.data.table_tennis,
              tableTennisLocalSupplier: response.data.table_tennis_local_supplier,
              tableTennisCharges: response.data.table_tennis_charges || null,
              volleyBall: response.data.volley_ball,
              volleyBallLocalSupplier: response.data.volley_ball_local_supplier,
              volleyBallCharges: response.data.volley_ball_charges || null,
              winterSportsActivitiesAvailable: response.data.winter_sports_activities_available,
              alpineSkiing: response.data.alpine_skiing,
              alpineSkiingLocalSupplier: response.data.alpine_skiing_local_supplier,
              alpineSkiingCharges: response.data.alpine_skiing_charges || null,
              crossCountrySkiing: response.data.cross_country_skiing,
              crossCountrySkiingLocalSupplier: response.data.cross_country_skiing_local_supplier,
              crossCountrySkiingCharges: response.data.cross_country_skiing_charges || null,
              snowBoarding: response.data.snow_boarding,
              snowBoardingLocalSupplier: response.data.snow_boarding_local_supplier,
              snowBoardingCharges: response.data.snow_boarding_charges || null,
              tobogganing: response.data.tobogganing,
              tobogganingLocalSupplier: response.data.tobogganing_local_supplier,
              tobogganingCharges: response.data.tobogganing_charges || null,
              otherSportsActivitiesAvailable: response.data.other_sports_activities_available,
              airHockey: response.data.air_hockey,
              airHockeyLocalSupplier: response.data.air_hockey_local_supplier,
              airHockeyCharges: response.data.air_hockey_charges || null,
              airRifleShooting: response.data.air_rifle_shooting,
              airRifleShootingLocalSupplier: response.data.air_rifle_shooting_local_supplier,
              airRifleShootingCharges: response.data.air_rifle_shooting_charges || null,
              archery: response.data.archery,
              archeryLocalSupplier: response.data.archery_local_supplier,
              archeryCharges: response.data.archery_charges || null,
              ballooning: response.data.ballooning,
              ballooningLocalSupplier: response.data.ballooning_local_supplier,
              ballooningCharges: response.data.ballooning_charges || null,
              bikeRental: response.data.bike_rental,
              bikeRentalLocalSupplier: response.data.bike_rental_local_supplier,
              bikeRentalCharges: response.data.bike_rental_charges || null,
              camelRiding: response.data.camel_riding,
              camelRidingLocalSupplier: response.data.camel_riding_local_supplier,
              camelRidingCharges: response.data.camel_riding_charges || null,
              carriageRides: response.data.carriage_rides,
              carriageRidesLocalSupplier: response.data.carriage_rides_local_supplier,
              carriageRidesCharges: response.data.carriage_rides_charges || null,
              climbing: response.data.climbing,
              climbingLocalSupplier: response.data.climbing_local_supplier,
              climbingCharges: response.data.climbing_charges || null,
              crossBowShooting: response.data.cross_bow_shooting,
              crossBowShootingLocalSupplier: response.data.cross_bow_shooting_local_supplier,
              crossBowShootingCharges: response.data.cross_bow_shooting_charges || null,
              darts: response.data.darts,
              dartsLocalSupplier: response.data.darts_local_supplier,
              dartsCharges: response.data.darts_charges || null,
              eBikeRental: response.data.e_bike_rental,
              eBikeRentalLocalSupplier: response.data.e_bike_rental_local_supplier,
              eBikeRentalCharges: response.data.e_bike_rental_charges || null,
              gameTown: response.data.game_town,
              gameTownLocalSupplier: response.data.game_town_local_supplier,
              gameTownCharges: response.data.game_town_charges || null,
              geoCoaching: response.data.geo_coaching,
              geoCoachingLocalSupplier: response.data.geo_coaching_local_supplier,
              geoCoachingCharges: response.data.geo_coaching_charges || null,
              giantChess: response.data.giant_chess,
              giantChessLocalSupplier: response.data.giant_chess_local_supplier,
              giantChessCharges: response.data.giant_chess_charges || null,
              guidedHikes: response.data.guided_hikes,
              guidedHikesLocalSupplier: response.data.guided_hikes_local_supplier,
              guidedHikesCharges: response.data.guided_hikes_charges || null,
              horseRiding: response.data.horse_riding,
              horseRidingLocalSupplier: response.data.horse_riding_local_supplier,
              horseRidingCharges: response.data.horse_riding_charges || null,
              laserBall: response.data.laser_ball,
              laserBallLocalSupplier: response.data.laser_ball_local_supplier,
              laserBallCharges: response.data.laser_ball_charges || null,
              multiFunctionalSpace: response.data.multi_functional_space,
              multiFunctionalSpaceLocalSupplier:
                response.data.multi_functional_space_local_supplier,
              multiFunctionalSpaceCharges: response.data.multi_functional_space_charges || null,
              paintBall: response.data.paint_ball,
              paintBallLocalSupplier: response.data.paint_ball_local_supplier,
              paintBallCharges: response.data.paint_ball_charges || null,
              paragliding: response.data.paragliding,
              paraglidingLocalSupplier: response.data.paragliding_local_supplier,
              paraglidingCharges: response.data.paragliding_charges || null,
              pilates: response.data.pilates,
              pilatesLocalSupplier: response.data.pilates_local_supplier,
              pilatesCharges: response.data.pilates_charges || null,
              quadRental: response.data.quad_rental,
              quadRentalLocalSupplier: response.data.quad_rental_local_supplier,
              quadRentalCharges: response.data.quad_rental_charges || null,
              segwayRental: response.data.segway_rental,
              segwayRentalLocalSupplier: response.data.segway_rental_local_supplier,
              segwayRentalCharges: response.data.segway_rental_charges || null,
              shuffleBoard: response.data.shuffle_board,
              shuffleBoardLocalSupplier: response.data.shuffle_board_local_supplier,
              shuffleBoardCharges: response.data.shuffle_board_charges || null,
              spinning: response.data.spinning,
              spinningLocalSupplier: response.data.spinning_local_supplier,
              spinningCharges: response.data.spinning_charges || null,
              summerToboGganing: response.data.summer_tobo_gganing,
              summerToboGganingLocalSupplier: response.data.summer_tobo_gganing_local_supplier,
              summerToboGganingCharges: response.data.summer_tobo_gganing_charges || null,
              tableFootBall: response.data.table_foot_ball,
              tableFootBallLocalSupplier: response.data.table_foot_ball_local_supplier,
              tableFootBallCharges: response.data.table_foot_ball_charges || null,
              towerJump: response.data.tower_jump,
              towerJumpLocalSupplier: response.data.tower_jump_local_supplier,
              towerJumpCharges: response.data.tower_jump_charges || null,
              yogaClass: response.data.yoga_class,
              yogaClassLocalSupplier: response.data.yoga_class_local_supplier,
              yogaClassCharges: response.data.yoga_class_charges || null,
              zipWire: response.data.zip_wire,
              zipWireLocalSupplier: response.data.zip_wire_local_supplier,
              zipWireCharges: response.data.zip_wire_charges || null,
              steamBath: response.data.steam_bath,
              steamBathAdmissionFrom: response.data.steam_bath_admission_from,
              steamBathCharges: response.data.steam_bath_charges || null,
              indoorSwimmingPool: response.data.indoor_swimming_pool,
              indoorSwimmingPoolCharges: response.data.indoor_swimming_pool_charges || null,
              indoorSwimmingPoolIsSeasonal: response.data.indoor_swimming_pool_is_seasonal,
              indoorSwimmingPoolCheck: response.data.indoor_swimming_pool_check,
              indoorSwimmingPoolFrom: response.data.indoor_swimming_pool_from,
              indoorSwimmingPoolTo: response.data.indoor_swimming_pool_to,
              saunas: response.data.saunas,
              saunasCount: response.data.saunas_count,
              saunasCharges: response.data.saunas_charges || null,
              saunasTypes: response.data.saunas_types || [],
              massages: response.data.massages,
              massagesTypes: response.data.massages_types || [],
              medicalTreatment: response.data.medical_treatment,
              medicalTreatmentTypes: response.data.medical_treatment_types || [],
              medicalTreatmentBathes: response.data.medical_treatment_bathes || [],
              beautyTreatment: response.data.beauty_treatment,
              wellnessBeautyTreatment: response.data.wellness_beauty_treatment || [],
            };
            context.commit("updateProperty", retrievedInfo);
            /* console.log("retrieved info data"); */
            resolve(retrievedInfo);
          })
          .catch((error) => {
            context.commit("updateProperty", {});
            reject(error);
            /* console.log("failed retrieve info data"); */
          });
      });
    },
  },
  getters: {
    getProperty(state) {
      return state.property;
    },
    getErrors(state) {
      return state.errors;
    },
  },
};
